"""FINAL_EXPERIMENT_CONFIG.json: the effective, frozen scientific configuration of the real Phase 2 run.

It is built from ``configs/meuhedet/phase2.yaml``, the feature catalogue and the code-level constants that change results (fold rules,
encodings, metric definitions, XGBoost / Optuna settings, gates). The repository copy ``configs/meuhedet/FINAL_EXPERIMENT_CONFIG.json`` and its
``.sha256`` are generated by ``tools/freeze_phase2_config.py`` after the final review; the runner rebuilds the effective configuration at every
start and refuses a run whose effective configuration differs from the frozen file (``FROZEN_CONFIG_MISMATCH``), unless an explicitly
non-production configuration is allowed (tests only; recorded and printed on every summary). Data-dependent facts (which columns are SAFE,
which features enter each set) are NOT in this file: they are computed by pre-declared rules and hashed in FEATURE_SETS.json.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from falls_ml.paths import resolve_path

FROZEN_PATH = "configs/meuhedet/FINAL_EXPERIMENT_CONFIG.json"
SCHEMA = "falls_ml.phase2.final_experiment_config/1"


def _rel(path: str | Path) -> str:
    """A path as the project declares it: relative paths unchanged (``/`` separators), absolute ones relative to the project root found from
    this module (never from the current working directory), else the file name - identical on every machine and working directory."""
    from falls_ml.paths import portable_path, project_relative_posix

    p = Path(path)
    if not p.is_absolute():
        return portable_path(p)
    return project_relative_posix(p, Path(__file__)) or p.name


def to_bytes(cfg: dict[str, Any]) -> bytes:
    return (json.dumps(cfg, indent=2, ensure_ascii=False, sort_keys=False) + "\n").encode("utf-8")


def sha256_of(cfg: dict[str, Any]) -> str:
    return hashlib.sha256(to_bytes(cfg)).hexdigest()


def build_final_config(cfg: Any, cat: Any, *, contract: Any, dictionary: Any, mapping: Any, d00: Any) -> dict[str, Any]:
    """The effective configuration (plain JSON). Every number the run uses is read from ``cfg`` or from the code constants imported here."""
    from falls_ml.phase2.config import FALL_RECENCY_BANDS, OTHER_NATIVE
    from falls_ml.phase2.design import FP_VARIABLES
    from falls_ml.phase2.evaluate import THRESHOLDS
    from falls_ml.phase2.featuresets import ALL_SAFE, BASELINE, EXPL_ALL, EXPL_B15_SAFE, SAFE_BASE
    from falls_ml.phase2.stages_models import BENCHMARK, CANDIDATE_KINDS, SAFE_REF

    c = cfg.raw
    x = c["xgb"]
    lasso, enet, cv = c["lasso"], c["enet"], c["cv"]
    K, Kl, Kx = int(cv["outer_folds"]), int(cv["inner_folds_linear"]), int(cv["inner_folds_xgb"])
    s1, s2 = x["stage1"], x["stage2"]
    scopes = K + 1
    fixed = dict(x["fixed"])
    n_domains = len(cat.domains)
    n_wf_named = len([w for w in cat.waterfall if w != OTHER_NATIVE])
    max_lasso_sets = 1 + 5 + n_domains + n_wf_named + 2
    return {
        "schema": SCHEMA,
        "name": "meuhedet_phase2_final_experiment_config",
        "status": "FROZEN for the real-data run (reviews/ASTRA_FINAL_RESOLUTION.md); any change requires a new review and a new freeze",
        "falls_ml_version": __import__("falls_ml").__version__,
        "sources": {
            "analysis_settings": {"path": _rel(cfg.path), "name": c.get("name"), "version": c.get("version"), "sha256": cfg.sha256},
            "feature_catalogue": {"path": _rel(cat.path), "name": cat.name, "version": cat.version, "sha256": cat.sha256},
            "d00_config": {"path": _rel(c["d00_config"]), "name": d00.name, "version": d00.version, "sha256": d00.sha256},
            "contract_sha256": contract.content_sha256, "data_dictionary_sha256": dictionary.sha256, "efalls_mapping_sha256": mapping.content_sha256,
        },
        "outcome": {"label": "Fall_Next_180D_Ind", "note": c.get("outcome_note"), "prediction_time": "START_OF_INDEX_DAY",
                    "predictor_record_rule": "source_event_date < Index_Date (unchanged D-00 rule; never weakened)",
                    "death_rule": "a recorded fall/fracture inside the window stays an event when death follows; death before any recorded event is a "
                                  "non-event; the warehouse label is audited on TRAIN+VALIDATION (label_death_audit) and the run stops "
                                  "(LABEL_DEATH_SEMANTICS) if deaths inside the window never carry an event (Astra F-05)",
                    "scope": "exploratory prediction of recorded events in the D00_CLEAN selected cohort (Astra F-03)"},
        "data_split_policy": {
            "cohort": "the reference meuhedet-explore D00_CLEAN cohort (age >= 65, one index date), rebuilt from the same extract and verified "
                      "row-for-row and value-for-value against the reference dataset",
            "split": "the reference patient-grouped split reproduced with the reference configuration; the TEST row-set sha256 must equal the "
                     "reference; the assignment is cross-checked against the reference splits.csv",
            "patient_overlap": "hard stop if any patient appears in more than one partition",
            "TRAIN": "all feature screening, redundancy, encoding decisions, tuning, feature/model selection, stability, ablation, SHAP",
            "VALIDATION": "sealed until SELECTION_FROZEN.json exists; opened ONCE (VALIDATION_OPENED.json) for a one-shot evaluation of the frozen "
                          "configurations; never used to choose, tune, recalibrate or threshold anything",
            "TEST": "identified during the split audit (count + sha256 only), dropped in memory before any other computation, never loaded again, "
                    "never used by Phase 2",
        },
        "cv_policy": {
            "outer": {"folds": K, "stratified_by_outcome": True, "grouped_by_patient": "one row per patient (the cohort has one index date)",
                      "seed": "rng_for(phase2.seed, 'phase2_outer_folds')", "repeats": 1},
            "inner_linear": {"folds": Kl, "assignment": "random permutation of patients (falls_ml.models.lasso_cv.assign_folds, grouped, not stratified)",
                             "seed": "the item seed", "used_for": "lambda (LASSO) and (l1_ratio, lambda) (elastic net) by minimum mean held-out deviance"},
            "inner_xgboost": {"folds": Kx, "stratified_by_outcome": True, "seed": "the item seed ('xgb_inner_folds')",
                              "used_for": "early stopping per inner fold (held-out log loss) and the Optuna objective (mean held-out log loss)"},
            "label_blind_steps_once_on_all_TRAIN": ["redundancy clusters (|Spearman| >= threshold, representative-anchored)",
                                                   "thermometer levels present", "NULL-pattern groups (na__ indicators)"],
            "fitted_inside_every_fold": ["eFalls preprocessor incl. fractional-polynomial selection for " + ", ".join(FP_VARIABLES),
                                         "median fills", "standardisation (LASSO / elastic net)", "hyper-parameters", "tree counts"],
            "common_inner_folds": "one inner-fold assignment per tuning scope (outer<k> / final), shared by every feature set, lambda, l1_ratio "
                                  "and Optuna trial of that scope (Astra F-07); booster randomness keeps the item seed",
            "conditionality": "the inner lambda search is conditional on the outer-training-fold FP choice; OOF results are conditional on the "
                              "TRAIN-wide label-blind decisions listed above (Astra F-07 / Q2)",
        },
        "seed_policy": {"master_seed": int(c["seed"]), "item_seed": "int(sha256(f'{seed}|{stage}|{item}')[:8], 16): independent of order and restarts",
                        "optuna_trial_seed": "sha256(f'{seed}|{study}|{trial_index}') mod 2^31-1 (sampler re-created per trial)",
                        "bootstrap_seed": "the item seed of the stage item that computes it",
                        "threads": {"blas": c["threads"]["blas"], "xgboost": c["threads"]["xgboost"], "max_auto": int(c["threads"]["max_auto"]),
                                    "rule": "auto = min(max_auto, os.cpu_count()); the resolved numbers are frozen in PHASE2_PLAN.json at the first start"}},
        "provenance_policy": {
            "rule": "the unchanged Phase 1 D-00 rules (falls_ml.d00.dependency._trace) on TRAIN + VALIDATION record dates; a feature takes the "
                    "worst status of its inputs (UNSAFE > UNRESOLVED > SAFE)",
            "UNSAFE": "excluded from every set ('candidate after DWH fix'); no row removal, no masking, no value replacement",
            "UNRESOLVED": "EXPLORATORY_UNRESOLVED_SENSITIVITY only; never in a SAFE_DISCOVERY set (hard stop INELIGIBLE_FEATURE_IN_SET)",
            "quarantine": dict(cat.quarantine), "represented_by": dict(cat.represented_by),
            "min_observed_train_rows": int(c["eligibility"]["min_observed_train_rows"]),
        },
        "categories": {
            "HISTORICAL_BASELINE_15": {"sets": [BASELINE], "definition": "the previous benchmark: the 15 EXTENDED predictors with unchanged "
                                       "definitions (provenance as found), refitted in the Phase 2 protocol; comparison only"},
            "SAFE_DISCOVERY": {"allowed_status": list(c["eligibility"]["categories"]["SAFE_DISCOVERY"]),
                               "definition": "PRIMARY: new and baseline features whose prediction-time provenance is proven SAFE"},
            "EXPLORATORY_UNRESOLVED_SENSITIVITY": {"allowed_status": list(c["eligibility"]["categories"]["EXPLORATORY_UNRESOLVED_SENSITIVITY"]),
                                                   "sets": [EXPL_B15_SAFE, EXPL_ALL], "families": ["LASSO"],
                                                   "definition": "separately labelled sensitivity; never a selection candidate; never UNSAFE"},
            "reporting_rule": "never mixed: separate tables / sections; every row carries its category",
        },
        "feature_set_definitions": {
            BASELINE: "the 15 EXTENDED predictors (HISTORICAL_BASELINE_15)",
            SAFE_BASE: "the BASELINE_15 predictors whose D-00 status is SAFE",
            "EFALLS_MAPPABLE_SAFE": "SAFE_BASE + SAFE non-redundant features with an eFalls mapping class",
            "MEUHEDET_NATIVE_SAFE": "SAFE_BASE + SAFE non-redundant Meuhedet-native features",
            ALL_SAFE: "SAFE_BASE + every SAFE non-redundant feature (= the last SAFE waterfall step = ALL_SAFE_LINEAR)",
            f"{ALL_SAFE}_WITHOUT_EXPLICIT_ASSESSMENT_FLAGS": "ALL_REVIEWED_SAFE without the explicit form 'assessed' indicators (sensitivity; "
                                                             "other NULL indicators stay, so missingness can still carry assessment information)",
            "SAFE_BASE_PLUS_<DOMAIN>": "SAFE_BASE + every SAFE feature of one domain (one-domain addition, not pruned)",
            "SAFE_WATERFALL_<k>_<DOMAIN>": "cumulative SAFE steps in the declared order: " + " -> ".join(cat.waterfall),
            f"{ALL_SAFE}_MINUS_<DOMAIN>": "ALL_REVIEWED_SAFE without one domain (leave-one-domain-out, fully nested)",
            EXPL_B15_SAFE: "BASELINE_15 (incl. its UNRESOLVED predictors) + every SAFE non-redundant feature (exploratory)",
            EXPL_ALL: "BASELINE_15 + every SAFE or UNRESOLVED non-redundant feature (exploratory)",
            "forms_rule": "a set with an item of an assessment form also holds that form's 'assessed' indicator (not measured != negative)",
            "aliases": "identical specifications share one fit (recorded in FEATURE_SETS.json)",
            "candidate_kinds": list(CANDIDATE_KINDS),
        },
        "encoding_policy": {
            "linear": {"binary": "1 if positive else 0; NULL covered by the form indicator, else an na__ indicator",
                       "ordinal": "thermometer dummies (>= level) for the declared levels present on TRAIN",
                       "count_days_amount": "log1p; NULL -> fold median + na__ indicator",
                       "fall_recency_bands": f"days since last fall: <= {FALL_RECENCY_BANDS[0]}, {FALL_RECENCY_BANDS[0] + 1}-{FALL_RECENCY_BANDS[1]}, "
                                             f"{FALL_RECENCY_BANDS[1] + 1}-{FALL_RECENCY_BANDS[2]}, > {FALL_RECENCY_BANDS[2]} (reference: no prior fall)",
                       "item_unanswered_min_share": float(c["screening"]["item_unanswered_min_share"]),
                       "baseline_block": "unchanged eFalls preprocessor (efalls_fp_all_levels; FP selection for age / polypharmacy inside each fold)",
                       "standardisation": "z-score of every design column on the fitting rows (inside the solver); coefficients reported on both scales",
                       "duplicate_columns": "exact duplicate design columns dropped inside each fold (first kept, recorded)"},
            "trees": "raw engineered values, NULL kept (native missing-value routing); sex -> female 0/1; form indicators included; no scaling, "
                     "no log, no thermometer, no imputation",
            "redundancy": {"abs_spearman": float(c["screening"]["redundancy_abs_spearman"]), "universes": "SAFE and exploratory separately",
                           "rule": "representative-anchored; representative = baseline feature, else lowest missingness, then catalogue order"},
        },
        "model_families": {
            "LASSO": {"implementation": "falls_ml.models.lasso_cv.LassoLogisticCV (Stata-equivalent penalised logistic regression)",
                      "penalty": "L1 on standardised coefficients; intercept unpenalised", "solver": "proximal-Newton (IRLS) + covariance-mode cyclic "
                      "coordinate descent, warm starts along the lambda path", "lambda_grid": {"n_lambda": int(lasso["n_lambda"]),
                      "lambda_min_ratio": float(lasso["lambda_min_ratio"]), "spacing": "log-uniform from lambda_max"},
                      "selection": {"rule": str(lasso["selection"]), "objective": "minimum mean held-out deviance (= 2 x log loss) over the inner folds"},
                      "cv_folds": Kl, "tol": float(lasso["tol"]), "max_iter": int(lasso["max_iter"]), "class_weight": "none",
                      "served_coefficients": "penalised (refit_unpenalized = false)",
                      "convergence_retry": "policy v1: one retry with a 10x full-path iteration limit at the same lambda*; never accepted unconverged"},
            "ELASTIC_NET": {"implementation": "falls_ml.phase2.enet.ElasticNetLogisticCV (glmnet parameterisation, same solver; = LASSO at l1_ratio 1)",
                            "l1_ratios": [float(a) for a in enet["l1_ratios"]], "n_lambda": int(enet["n_lambda"]),
                            "lambda_min_ratio": float(lasso["lambda_min_ratio"]), "selection": "joint (l1_ratio, lambda) by minimum inner-CV mean deviance",
                            "cv_folds": Kl, "tol": float(lasso["tol"]), "max_iter": int(lasso["max_iter"]), "class_weight": "none",
                            "sets": f"ALL_REVIEWED_SAFE + the best SAFE LASSO set by outer-OOF AP (max {int(enet['max_sets'])})"},
            "XGBOOST": {"library": "xgboost 3.2.0 (xgboost-cpu wheel on Windows)", "api": "xgboost.train (native)",
                        "fixed_parameters": fixed, "base_score_note": "auto = estimated by xgboost from the fitting rows' labels (not passed)",
                        "per_fit": {"seed": "item seed mod 2^31-1", "nthread": "resolved threads.xgboost", "verbosity": 0},
                        "num_boost_round_ceiling": int(x["n_estimators_max"]), "early_stopping_rounds": int(x["early_stopping_rounds"]),
                        "early_stopping": "xgb.train(num_boost_round=ceiling, evals=[inner held-out fold], early_stopping_rounds); the inner held-out "
                                          "fold is scored with iteration_range=(0, best_iteration+1) (the native API returns the LAST model); the final "
                                          "fit of a scope = median inner best iteration + 1 trees on all its training rows, WITHOUT early stopping; outer "
                                          "held-out rows never seen (Astra F-01)",
                        "stage0": {"params": {k: x["stage0"][k] for k in ("max_depth", "min_child_weight", "reg_lambda")},
                                   "sets": list(x["stage0"]["sets"])},
                        "stage1": {"set": s1["set"], "n_trials_per_scope": int(s1["n_trials"]), "n_startup_trials": int(s1["n_startup_trials"]),
                                   "space": s1["space"]},
                        "stage2": {"enabled": bool(s2.get("enabled", True)), "n_trials_per_scope": int(s2["n_trials"]),
                                   "local_factor": float(s2["local_factor"]), "space_added": s2["space"],
                                   "depth_rule": "{best-1, best, best+1} intersected with the stage-1 range (never 0)",
                                   "condition": f"stage-1 outer-OOF AP >= best SAFE linear outer-OOF AP + {s2['condition_min_ap_gain_vs_best_linear']}",
                                   "local_space": "max_depth +/-1 and min_child_weight / reg_lambda within best/factor..best*factor of the scope's "
                                                  "stage-1 best (clipped to the stage-1 range)"},
                        "max_trials_per_study": int(x["max_trials_per_study"]), "tuning_scopes": f"{K} outer folds + 1 final = {scopes}",
                        "class_weighting": "none (scale_pos_weight 1)", "monotone_constraints": "none", "deterministic": "hist on CPU with a fixed "
                        "thread count and seed (checked bit-for-bit by the preflight self-test)"},
        },
        "optuna": {**x["optuna"], "n_startup_trials": int(s1["n_startup_trials"]), "stage2_n_startup_trials": max(2, int(s2["n_trials"]) // 3),
                   "failure_handling": "a trial is a committed item; an interrupted trial leaves no trace (study rebuilt from committed trials); "
                                       "a trial error stops the run (no silent FAIL state)",
                   "promotion_metric": "stage 1 -> stage 2 and XGBoost vs linear: outer-OOF AP (never VALIDATION)"},
        "selection": {**{k: v for k, v in c["selection"].items()}, "rule": (
            "a SAFE_DISCOVERY candidate (kinds " + ", ".join(CANDIDATE_KINDS) + f"; families LASSO / ENET / XGBOOST) qualifies vs {SAFE_REF} if ALL "
            "of: dAP >= min_delta_ap, d capture@principal >= min_delta_capture_principal_pp, log loss <= max_logloss_ratio x reference, OOF "
            "calibration slope within calibration_slope_range and |CITL| <= max_abs_citl; recommended = the simplest (linear before XGBoost, then "
            f"fewer features used) within simplicity_margin_ap of the best qualifying OOF AP, else {SAFE_REF}. The recommended model is then "
            f"classified vs {BENCHMARK}: SUPERIOR (meets the same rule), NON_INFERIOR (dAP >= -max_ap_loss and d capture >= -max_capture_loss_pp), "
            "else INFERIOR. Frozen in SELECTION_FROZEN.json before VALIDATION is opened."),
            "benchmark_classes": ["MEETS_SUPERIORITY_RULE", "WITHIN_NONINFERIORITY_MARGINS", "OUTSIDE_MARGINS"],
            "benchmark_class_kind": "point-estimate classification, not a formal superiority / non-inferiority test (Astra F-03)",
            "benchmark_identity": "LASSO:BASELINE_15 = the 15 historical predictors refitted on TRAIN in the Phase 2 protocol, no recalibration; "
                                  "not the Phase 1 model recalibrated on VALIDATION (Astra F-02)",
            "no_selection_outcome": "NO_INCREMENTAL_MODEL_SELECTED (SAFE_BASE is reported, never self-compared; Astra F-08)",
            "undefined_values": "an undefined (NaN) quantity never passes a rule (Astra F-08)",
            "attribution_contrasts": {"FEATURE_EXPANSION": "LASSO:ALL_REVIEWED_SAFE vs LASSO:SAFE_BASE",
                                      "MODEL_FAMILY_PIPELINE": "XGB_TUNED:ALL_REVIEWED_SAFE vs the TRAIN-selected best linear model on ALL_REVIEWED_SAFE",
                                      "note": "frozen before VALIDATION; paired intervals on OOF and VALIDATION; no extra fits (Astra F-09)"},
            "shortlist": f"{SAFE_REF}, {BENCHMARK}, the recommended model, then the best SAFE candidate of each other family (<= max_challengers)"},
        "validation": {**c["validation_confirmation"], "rule": (
            "one-shot exploratory screen on reused VALIDATION: recommended vs SAFE_BASE -> CONFIRMED_PROMISING if dAP >= min_delta_ap, "
            "d capture@principal >= min pp, log loss <= max_logloss_ratio x SAFE_BASE and calibration within range (NaN never passes), else "
            "NOT_CONFIRMED; point-estimate class vs the BASELINE_15 refit with the same superiority margins and the non-inferiority margins; every "
            "frozen configuration is also scored descriptively on the same rows"),
            "artifacts": ["VALIDATION_OPENED.json (write-once)", "validation_evaluation_registry.jsonl (append-only)"]},
        "metrics": {"primary": "average precision (AP = PR-AUC, step-wise, sklearn-equivalent, ties grouped)",
                    "secondary": ["log loss (proper scoring rule; tuning objective and safeguard)", "AUROC", "Brier", "scaled Brier (1 - Brier / "
                                  "Brier of the prevalence)", "calibration-in-the-large (CITL, slope fixed at 1)", "calibration intercept and slope "
                                  "(logistic recalibration of the logit)", "O:E"],
                    "capacities": [float(v) for v in c["metrics"]["capacities"]], "principal_capacity": float(c["selection"]["principal_capacity"]),
                    "capacity_rule": "ceil(capacity x n) highest risks; ties keep row order; identical rule for every model on the same rows",
                    "per_capacity": ["falls identified (tp)", "sensitivity (capture)", "PPV", "false alerts (fp)", "lift", "specificity", "NPV"],
                    "thresholds": list(THRESHOLDS), "calibration_groups": int(c["metrics"]["calibration_groups"]),
                    "paired_bootstrap": {"n": int(c["metrics"]["bootstrap_n"]), "unit": "patient (one row per patient)", "interval": "percentile 95%",
                                         "same_patients_both_models": True, "top_n_recomputed_per_replicate": True,
                                         "per_capacity": "difference in recorded events identified at every capacity, also per 10,000 comparable D00_CLEAN "
                                                         "patients (Astra F-12)",
                                         "note": "describes sampling variation of frozen predictions; does not account for the model search"},
                    "definitions": {"scaled_brier": "1 - Brier / [p_eval (1 - p_eval)], p_eval = prevalence of the evaluated rows", "oe": "sum(y) / sum(p)",
                                    "citl": "a in logit P(y=1) = a + 1 x logit(p) (offset)", "calibration": "logit P(y=1) = a + b logit(p)"},
                    "subgroup_min_events": int(c["metrics"]["subgroup_min_events"]), "small_cell_suppression": int(c["screening"]["min_cell"])},
        "calibration_policy": {"no_recalibration": "no model is recalibrated in Phase 2 (no calibration data independent of VALIDATION exists)",
                               "evaluated": "every configuration: CITL, slope, intercept, O:E, Brier, scaled Brier (OOF and VALIDATION); for the shortlist "
                                            "and the management waterfall: bootstrap intervals of these indices and a smooth calibration curve "
                                            "(restricted cubic spline of logit(p), 95% band) with decile points (Astra F-11)",
                               "smooth_curve": dict(c["metrics"].get("smooth_calibration") or {}),
                               "class_weighting": "none, so predicted probabilities stay on the risk scale"},
        "stability": {**c["stability"], "method": "LASSO on bootstrap resamples of TRAIN (inner CV repeated, copies of a resampled patient kept "
                      "in one inner fold); selection count, frequency with Monte Carlo SE, sign consistency; LASSO only - never certifies "
                      "elastic-net-only or XGBoost findings (Astra F-13)", "sets": "finalists only: SAFE linear shortlist sets, ALL_REVIEWED_SAFE, then "
                      "BASELINE_15 (max_sets)", "feature_selected": "any of its encoded design columns non-zero"},
        "ablation": {**c["ablation"], "leave_one_domain_out": "LASSO, fully nested (retuned), vs LASSO:ALL_REVIEWED_SAFE on the same outer folds",
                     "individual": "top-N new features of the recommended SAFE model (or the best SAFE model with new features) by final-model "
                                   "importance, refitted without the feature with the fold's frozen hyper-parameters (explanatory)"},
        "explainability": {**c["explain"], "target": "the XGBoost member of the frozen shortlist (if any)",
                           "permutation": "per outer fold, on that fold's held-out rows, with that fold's booster; delta AP and delta log loss",
                           "shap": "TreeSHAP (pred_contribs) of the final booster on a class-stratified TRAIN sample; aggregated quantiles only "
                                   "(no per-patient points leave the PC)"},
        "consensus": {**dict(c["consensus"]), "label": "exploratory predictive evidence (not causal)",
                      "classes": "U univariate; L = LASSO selection with LASSO stability >= linear_min_stability; I = SHAP rank <= shap_top_rank "
                                 "of the promoted XGBoost; permutation gain > 0 alone and elastic-net-only selection = weak support; A_dom one-domain "
                                 "gain >= domain_min_delta_ap; A_feat individual ablation >= ablation_min_delta_ap",
                      "ratings": "STRONG = A_feat and (L or I); MODERATE = (L or I) and (U or A_dom), or A_feat; WEAK = any single support; NONE"},
        "stop_gates": {
            "hard": ["INPUT_MISSING", "PROTECTED_MISSING", "OUT_INSIDE_PROTECTED", "SYNCED_FOLDER", "OUT_NOT_EMPTY", "NOTHING_TO_RESUME",
                     "FROZEN_CONFIG_MISMATCH", "INPUT_CHANGED", "PLAN_CHANGED", "CODE_CHANGED", "REFERENCE_INVALID", "INPUT_NOT_REFERENCE",
                     "PEPPER_MISSING", "PEPPER_MISMATCH", "COHORT_MISMATCH", "COHORT_VALUES_DIFFER", "SPLIT_MISMATCH", "PATIENT_OVERLAP",
                     "ROW_MAPPING", "LABEL_MISMATCH", "INELIGIBLE_FEATURE_IN_SET", "PROTECTED_CHANGED", "COMPLETED_ARTIFACT_CHANGED",
                     "STAGE_ORDER", "OOF_INCOMPLETE", "FIT_FAILURES", "REFERENCE_FAILED", "VALIDATION_CONFIG_MISMATCH", "VALIDATION_REOPEN_REFUSED",
                     "SELFTEST_FAILED", "DEPENDENCY_MISSING", "WORDING", "PRIVACY_SCAN"],
            "investigation": {"LABEL_DEATH_SEMANTICS": "deaths inside the 180-day window (>= 50) never carry a recorded event (possible overwrite "
                                                       "of prior events by death; Astra F-05)",
                              "SINGLE_FEATURE_DOMINANCE": f"a new feature with TRAIN univariate AUROC >= {c['gates']['single_feature_univariate_auroc']} (or its mirror)",
                              "IMPLAUSIBLE_GAIN_OOF": f"any SAFE / exploratory configuration vs BASELINE_15 on TRAIN OOF: dAUROC > {c['gates']['max_delta_auroc']} or AP ratio > {c['gates']['max_ap_ratio']}",
                              "IMPLAUSIBLE_CALIBRATION_OOF": f"recommended model OOF slope outside {c['gates']['calibration_slope_range']} or |CITL| > {c['gates']['max_abs_citl']}",
                              "PROXY_DOMINANCE": f"one new feature > {c['gates']['max_single_feature_share']:.0%} of mean |SHAP| or of the permutation AP loss of the promoted XGBoost",
                              "IMPLAUSIBLE_GAIN_VALIDATION": "same limits as the OOF gate, on VALIDATION",
                              "IMPLAUSIBLE_CALIBRATION_VALIDATION": "a shortlist model's VALIDATION calibration outside the gate range"},
            "gate_values": dict(c["gates"]),
            "acceptance": "never automatic: --resume --accept-gate <GATE> --reason \"...\" after reviewing INVESTIGATION_<GATE>.md (recorded)"},
        "compute_budget": {
            "max_lasso_sets": max_lasso_sets, "lasso_fits_per_set": f"{K} outer + 1 final, each with a {Kl}-fold path CV",
            "enet_fits": f"<= {int(enet['max_sets'])} sets x {K + 1} fits x {len(enet['l1_ratios'])} l1_ratios x {Kl}-fold path CV",
            "xgb_stage0_fits": f"{len(x['stage0']['sets'])} sets x {scopes} scopes x ({Kx} inner + 1 final)",
            "xgb_stage1_trials": int(s1["n_trials"]) * scopes,
            "xgb_stage2_trials_max": int(s2["n_trials"]) * scopes if s2.get("enabled", True) else 0,
            "xgb_trials_total_max": (int(s1["n_trials"]) + (int(s2["n_trials"]) if s2.get("enabled", True) else 0)) * scopes,
            "xgb_inner_booster_fits_stage1": int(s1["n_trials"]) * scopes * Kx,
            "stability_fits": int(c["stability"]["n_replicates"]) * int(c["stability"]["max_sets"]),
            "ablation_fits_max": f"<= {n_domains} domains x {K} + {int(c['ablation']['individual_top_n'])} features x {K}",
            "bootstrap_replicates_per_comparison": int(c["metrics"]["bootstrap_n"]),
        },
        "catalogue": {"domains": {k: v["label"] for k, v in cat.domains.items()}, "waterfall": list(cat.waterfall), "forms": cat.forms,
                      "features": [{"name": f.name, "domain": f.domain, "op": f.op, "inputs": list(f.inputs), "kind": f.kind, "linear": f.linear,
                                    "missing": f.missing, "mapping_class": f.mapping_class, **({"threshold": f.threshold} if f.threshold is not None else {}),
                                    **({"levels": list(f.levels)} if f.levels else {})} for f in cat.features]},
    }


def load_frozen() -> tuple[bytes | None, str | None]:
    """(bytes, sha256) of the repository's frozen FINAL_EXPERIMENT_CONFIG.json, or (None, None) when it is missing."""
    p = resolve_path(FROZEN_PATH)
    if not p.is_file():
        return None, None
    b = p.read_bytes()
    return b, hashlib.sha256(b).hexdigest()


def sha_line(sha: str) -> str:
    return f"{sha}  FINAL_EXPERIMENT_CONFIG.json\n"
