"""PHASE3_FINAL_EXPERIMENT_CONFIG.json: the effective, frozen scientific configuration of the real Phase 3 run (settings + recovery rules + the
unchanged catalogue + the result-relevant code constants). Generated by ``tools/freeze_phase3_config.py``; the runner and the preflight refuse any
other effective configuration (PHASE3_FROZEN_CONFIG_MISMATCH) unless ``--allow-unfrozen-config`` (tests only; flagged everywhere). Independent of
the Phase 2 freeze, which it never reads or changes."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from falls_ml.paths import resolve_path

FROZEN_PATH = "configs/meuhedet/PHASE3_FINAL_EXPERIMENT_CONFIG.json"
SCHEMA = "falls_ml.phase3.final_experiment_config/1"


def _rel(path: str | Path) -> str:
    from falls_ml.paths import portable_path, project_relative_posix

    p = Path(path)
    return portable_path(p) if not p.is_absolute() else (project_relative_posix(p, Path(__file__)) or p.name)


def to_bytes(cfg: dict[str, Any]) -> bytes:
    return (json.dumps(cfg, indent=2, ensure_ascii=False, sort_keys=False) + "\n").encode("utf-8")


def sha256_of(cfg: dict[str, Any]) -> str:
    return hashlib.sha256(to_bytes(cfg)).hexdigest()


def sha_line(sha: str) -> str:
    return f"{sha}  PHASE3_FINAL_EXPERIMENT_CONFIG.json\n"


def load_frozen() -> tuple[bytes | None, str | None]:
    from falls_ml.errors import ConfigError

    try:
        p = resolve_path(FROZEN_PATH)
    except ConfigError:
        return None, None
    if not p.is_file():
        return None, None
    data = p.read_bytes().replace(b"\r\n", b"\n")
    return data, hashlib.sha256(data).hexdigest()


def build_final_config(cfg: Any, rules: Any, cat: Any, *, contract: Any, dictionary: Any, mapping: Any, d00: Any, tc: Any) -> dict[str, Any]:
    from falls_ml.phase3 import PHASE3_VERSION
    from falls_ml.phase3 import bounds, recovery
    from falls_ml.phase3.stages_models import CANDIDATE_KINDS, INCONCLUSIVE, INCREMENTAL, NONE, REF

    c = cfg.raw
    return {
        "schema": SCHEMA, "name": "meuhedet_phase3_final_experiment_config",
        "status": "FROZEN for the real-data Phase 3 run before any Phase 3 result and before any Phase 2 VALIDATION result was returned; any change needs a new freeze",
        "phase3_version": PHASE3_VERSION, "falls_ml_version": __import__("falls_ml").__version__,
        "sources": {"analysis_settings": {"path": _rel(cfg.path), "version": c.get("version"), "sha256": cfg.sha256},
                    "recovery_rules": {"path": _rel(rules.path), "version": rules.version, "sha256": rules.sha256},
                    "time_contract": {"path": _rel(tc.path), "sha256": tc.sha256},
                    "feature_catalogue_unchanged_from_phase2": {"path": _rel(cat.path), "version": cat.version, "sha256": cat.sha256},
                    "d00_config": {"path": _rel(c["d00_config"]), "version": d00.version, "sha256": d00.sha256},
                    "contract_sha256": contract.content_sha256, "data_dictionary_sha256": dictionary.sha256, "efalls_mapping_sha256": mapping.content_sha256},
        "outcome": {"label": "Fall_Next_180D_Ind", "note": c.get("outcome_note"), "prediction_time": "END_OF_INDEX_DAY",
                    "predictor_record_rule": "source_event_date <= Index_Date", "outcome_window": "Index_Date + 1 day .. Label_End_180D"},
        "time_contract": tc.raw["phase3_time_contract"], "standards": c["standards"],
        "population": c["population"],
        "partitions": {"TRAIN": "every recovery gate, screening, tuning, selection, stability, ablation; the primary internal estimate (outer OOF)",
                       "VALIDATION": "REUSED: sealed until SELECTION_FROZEN.json; one-shot descriptive check; never selects, tunes or recalibrates",
                       "TEST": "dropped in memory right after the reference split hash check (and TEST-assigned D-00 rows likewise); never read"},
        "recovery": {"rules": rules.raw, "row_recoverable_evidence_kind": "COMPLETE_RECORD_DATE with a DOCUMENTED record date",
                     "classes": recovery.CLASS_TEXT, "known_unknown_rule": recovery.__doc__.split("Per row and feature:")[1].split("Nothing is repaired")[0].strip()},
        "bounds": {"method": "partial identification over the observed pre-index states of the fitting rows, cumulative upper bounds applied",
                   "linear": "exact min / max (per-source additive contributions)", "xgboost": "sound outer bound (interval propagation through every tree)",
                   "max_profiles_per_source": bounds.MAX_PROFILES, "fit_rows": "rows whose every scope feature is KNOWN",
                   "evaluation_rows": "every row", "adverse": "events lowest, non-events highest possible risk", "favourable": "the reverse",
                   "comparison": "adverse difference = new adverse - reference favourable"},
        "feasibility": c["feasibility"],
        "selection": {**c["selection"], "candidate_kinds": list(CANDIDATE_KINDS), "reference_config": REF, "outcomes": [INCREMENTAL, INCONCLUSIVE, NONE],
                      "decision_bound": "ADVERSE"},
        "validation_confirmation": c["validation_confirmation"],
        "models": {"cv": c["cv"], "lasso": c["lasso"], "enet": c["enet"], "xgb": c["xgb"]},
        "stability": c["stability"], "ablation": c["ablation"], "explain": c["explain"], "metrics": c["metrics"], "gates": c["gates"],
        "screening": c["screening"], "eligibility": c["eligibility"], "seed": int(c["seed"]), "threads": c["threads"],
    }
