"""Generate a feature spec that keeps the 78 eFalls candidate predictors of ``configs/features/efalls_v1.yaml`` byte-for-byte
and replaces ONLY the outcome block with the Meuhedet 180-day EXPLORATORY outcome (spec §11 M-02; Phase 1).

The generated spec is NOT an eFalls outcome: it exists so that the published learning process can be exercised on the
wide table's 180-day label while the 365-day ED/admission outcome is being built. ``--check`` verifies the file is current.
Usage: python tools/generate_exploratory_outcome_spec.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "configs" / "features" / "efalls_v1.yaml"
OUT = ROOT / "configs" / "features" / "efalls_v1__outcome_fall_next_180d_exploratory.yaml"
MAPPING = ROOT / "configs" / "meuhedet" / "wide_v1_efalls_mapping.yaml"
HEADER = (
    "# GENERATED by tools/generate_exploratory_outcome_spec.py from configs/features/efalls_v1.yaml - do not edit by hand.\n"
    "# Predictors: the 78 eFalls candidates, unchanged. Outcome: Meuhedet 180-day EXPLORATORY label (Fall_Next_180D_Ind of\n"
    "# V_Falls_Prediction_Wide_1 V1.0) - NOT the eFalls outcome (ED attendance or hospital admission with fall/fracture within\n"
    "# 12 months). Any experiment on this spec is 'Meuhedet 180-day exploratory - NOT eFalls reproduction'.\n"
)


def build() -> str:
    base = yaml.safe_load(BASE.read_text(encoding="utf-8"))
    mapping = yaml.safe_load(MAPPING.read_text(encoding="utf-8"))["outcome"]
    fs = base["feature_set"]
    base["feature_set"] = {**fs, "name": f"{fs['name']}__outcome_fall_next_180d_exploratory",
                           "version": f"{fs['version']}-exploratory180d",
                           "outcome_note": "EXPLORATORY 180-day Meuhedet outcome; predictors identical to efalls_v1"}
    base["outcome"] = {
        "name": mapping["canonical_name"],
        "dtype": "binary",
        "layer": "L3a_meuhedet_exploratory_outcome",
        "status": "EXPLORATORY - NOT the eFalls outcome",
        "concept": ("Any fall/fracture event recorded in Meuhedet sources within 180 days after the index date "
                    "(V_Falls_Prediction_Wide_1 Fall_Next_180D_Ind, Definition_Version V1.0); encounter setting (ED/admission) "
                    "and code list NOT verified against eFalls (spec §11 M-02, M-08)"),
        "window": {"start": "index_date (inclusive)", "end": f"index_date + {mapping['window_days_including_index'] - 1} days (inclusive)",
                   "horizon_days": int(mapping["window_days_including_index"]), "decision": "Meuhedet VIEW label window (Label_End_180D)"},
        "source_columns": {"label": mapping["label_column"], "event_date": mapping["event_date_column"],
                           "window_end": mapping["window_end_column"], "label_reason": mapping["label_reason_column"]},
        "censoring": mapping["censored_rows"],
        "deaths": mapping["deaths"],
        "efalls_outcome_blockers": list(mapping["efalls_outcome_blockers"]),
        "code_system": "Meuhedet fall/fracture event list V1.0 (not documented against eFalls)",
        "codes": [],
        "meuhedet_source": {"mapping_file": "configs/meuhedet/wide_v1_efalls_mapping.yaml", "status": "EXPLORATORY",
                            "clinically_validated": False},
        "clinically_validated": False,
    }
    return HEADER + yaml.safe_dump(base, sort_keys=False, allow_unicode=True, width=120)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if the generated file is out of date")
    a = ap.parse_args(argv)
    text = build()
    if a.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else None
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is out of date; run python tools/generate_exploratory_outcome_spec.py", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} is current")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
