"""Render the Meuhedet Phase-1 deliverable tables from the machine-readable manifests (never edit the .md/.csv by hand).

Inputs:  configs/meuhedet/wide_v1_columns.yaml, configs/meuhedet/wide_v1_efalls_mapping.yaml, configs/features/efalls_v1.yaml
Outputs: docs/meuhedet/MAPPING_TABLE.md, COLUMN_INVENTORY.md, DATATYPE_CONTRACT.md and docs/meuhedet/tables/*.csv
Usage:   python tools/generate_meuhedet_docs.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from falls_ml.data.meuhedet_wide import (DEFAULT_CONTRACT, DEFAULT_MAPPING, column_inventory_table, load_wide_contract,  # noqa: E402
                                         load_wide_mapping, mapping_table)
from falls_ml.features.spec import load_feature_spec  # noqa: E402

OUT = ROOT / "docs" / "meuhedet"
TABLES = OUT / "tables"
HEADER = "<!-- GENERATED by tools/generate_meuhedet_docs.py from configs/meuhedet/*.yaml - do not edit by hand -->\n"

SEMANTIC_RULES = [
    ("identifier", "string", "never", "never enters a model matrix; never printed by the audit"),
    ("date", "datetime64[us] (contract layer, full SQL date range 0001..9999) → datetime64[ns] for the canonical modelling dates only", "never",
     "raw dates never enter a model; derived Days_Since_* columns do; used for the D-00 timing check; far-future business sentinels "
     "(e.g. 2999-12-31 = open-ended SCD row) stay dates and must be declared per column (sentinels / sentinel_means / sentinel_modeling_rule); "
     "an undeclared far-future date in a column the build uses stops the build naming column, value and expected type"),
    ("binary", "Int64 (nullable)", "int8_binary", "allowed {0,1}; NULL keeps its business meaning (not assessed / source absent); 0 only by a declared eFalls absent_is_zero rule"),
    ("count", "Int64 (nullable)", "float64", "non-negative integers; NULL = source absent / not applicable (declared per column)"),
    ("continuous", "float64 / Int64", "float64", "numeric; NULL = not measured (missing indicator + training-derived imputation in Phase 2)"),
    ("categorical", "Int64 or string", "onehot_categorical", "codes are labels, never magnitudes; one-hot encoded; NULL = missing category when declared"),
    ("ordinal", "Int64 / float64", "ordinal_float64", "ordered score with a declared range; NULL = not assessed (missing category)"),
    ("quality_control", "Int64 / string", "never", "QA / control field; audited, never a predictor"),
    ("label", "Int64 / string", "never", "outcome and outcome-support columns; never a predictor"),
]


def _md(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, r in df.iterrows():
        lines.append("| " + " | ".join(str("" if pd.isna(v) else v).replace("|", "/").replace("\n", " ") for v in r.tolist()) + " |")
    return "\n".join(lines) + "\n"


def build() -> dict[Path, str]:
    contract = load_wide_contract(DEFAULT_CONTRACT)
    spec = load_feature_spec(ROOT / "configs" / "features" / "efalls_v1.yaml")
    mapping = load_wide_mapping(DEFAULT_MAPPING, spec=spec, contract=contract)
    cov = mapping.coverage(spec)
    mt = mapping_table(mapping)
    it = column_inventory_table(contract)
    files: dict[Path, str] = {}
    files[TABLES / "efalls_meuhedet_mapping.csv"] = mt.to_csv(index=False, lineterminator="\n")
    files[TABLES / "wide_v1_column_inventory.csv"] = it.to_csv(index=False, lineterminator="\n")

    quality_rows = [{"quality": q, "meaning": m} for q, m in (
        ("EXACT", "same concept, same operational definition, same window and representation"),
        ("HIGH_CONFIDENCE", "same clinical concept; comparable population-wide operationalisation (e.g. disease registry); meaning unlikely to change"),
        ("APPROXIMATE", "same construct, materially different operationalisation (window, unit, ascertainment, subset)"),
        ("UNAVAILABLE", "no population-wide pre-index source in the wide table (assessment-conditional nurse fields do not qualify)"))]
    included = mt[mt["include_in_baseline"]][["canonical_feature", "efalls_definition", "meuhedet_source_column", "mapping_quality", "raw_dtype",
                                              "canonical_dtype", "model_dtype", "missing_rule", "transformation", "lookback_window", "notes"]]
    unavailable = mt[~mt["include_in_baseline"]][["canonical_feature", "efalls_definition", "mandatory", "phase2_candidate", "notes"]]
    mapping_md = (HEADER + f"# eFalls → Meuhedet mapping table (mapping {mapping.name} {mapping.version}; spec {spec.name} {spec.version})\n\n"
                  f"**Status:** {mapping.status}. Mapping manifest sha256 `{mapping.content_sha256}`; feature-spec sha256 `{spec.content_sha256}`; "
                  f"contract `{contract.name} {contract.version}` sha256 `{contract.content_sha256}`.\n\n"
                  "## Coverage (denominator derived from the feature spec, not hard-coded)\n\n"
                  f"- expected eFalls predictors: **{cov['n_expected']}** ({spec.name} {spec.version})\n"
                  f"- available for the baseline: **{cov['n_available']} ({cov['coverage_pct']}%)** = exact {cov['n_exact']} + high-confidence "
                  f"{cov['n_high_confidence']} + approximate {cov['n_approximate']}\n"
                  f"- unavailable: {cov['n_unavailable']}\n- mandatory eFalls predictors unavailable: **{', '.join(cov['mandatory_unavailable'])}**\n"
                  f"- published-model predictors available: {cov['n_published_retained_available']} of {cov['n_published_retained_total']}\n"
                  f"- **{cov['label']}**\n\n## Quality levels\n\n" + _md(pd.DataFrame(quality_rows)) +
                  "\n## Included in the baseline\n\n" + _md(included) + "\n## Unavailable for the baseline\n\n" + _md(unavailable) +
                  "\n## Open questions for the Meuhedet team\n\n" + "".join(f"- **{k}**: {v}\n" for k, v in mapping.open_questions.items()) +
                  "\n## Outcome\n\n- canonical exploratory outcome: `" + mapping.outcome["canonical_name"] + "` ← `" + mapping.outcome["label_column"] +
                  f"` (window {mapping.outcome['window_days_including_index']} days including the index day; censored rows: {mapping.outcome['censored_rows']})\n"
                  "- eFalls 365-day outcome blockers:\n" + "".join(f"  - {b}\n" for b in mapping.outcome["efalls_outcome_blockers"]) +
                  "\nFull table with every manifest column: `tables/efalls_meuhedet_mapping.csv`.\n")
    files[OUT / "MAPPING_TABLE.md"] = mapping_md

    role_counts = it["role"].value_counts()
    inv_md = (HEADER + f"# Feature-role inventory of {contract.source_view} (contract {contract.name} {contract.version}, {len(it)} columns)\n\n"
              "Every column has exactly one role. Predictor roles need `timing` pre_index or at_index; `unknown` timing blocks a column until "
              "data engineering confirms its as-of semantics; FORBIDDEN_LEAKAGE, LABEL, QA_CONTROL, COHORT_ELIGIBILITY and IDENTIFIER columns can "
              "never enter a model matrix.\n\n## Roles\n\n" + _md(pd.DataFrame({"role": role_counts.index, "n_columns": role_counts.to_numpy()})) +
              "\n## Columns\n\n" + _md(it[["column", "sql_type", "ddl_nullable", "role", "semantic_type", "model_dtype", "timing", "allowed_values",
                                            "null_means", "sentinels", "sentinel_means", "phase2_group", "note"]]) + "\nCSV: `tables/wide_v1_column_inventory.csv`.\n")
    files[OUT / "COLUMN_INVENTORY.md"] = inv_md

    pred = it[it["predictor_allowed"] | (it["role"] == "EFALLS_BASELINE_FEATURE")][["column", "sql_type", "semantic_type", "model_dtype", "allowed_values", "null_means", "role"]]
    dt_md = (HEADER + "# Datatype contract (raw SQL type → canonical semantic type → model-matrix type)\n\n"
             "Types are declared, never inferred: `falls_ml.data.meuhedet_wide.coerce_wide_types` casts every column to the declared pandas dtype "
             "and reports each value that does not fit (`wrong_type`, with the offending values for date columns); the build stops on any wrong-type value in a column it uses. "
             "Date text is read only with the source layouts the contract declares (`contract.date_formats`, in trial order), so 01/02/2024 has exactly one "
             "meaning; the loader refuses a set in which two formats would read the same text differently (no day/month inference), and anything no declared "
             "format fits is a counted wrong-type value, never a guess or an Excel serial number. Dates land in `datetime64[us]`, which holds the whole SQL date range; "
             "only the canonical modelling dates (index_date, predictor_max_record_date, outcome_first_event_date, death_date, followup_end_date) are cast to "
             "`datetime64[ns]`, and a value that range cannot hold is never converted silently. "
             "`NULL` is never converted to 0 unless the mapping manifest declares the eFalls `absent_is_zero` rule for that predictor, and every "
             "such conversion is counted in the build report.\n\n## Semantic types\n\n" +
             _md(pd.DataFrame(SEMANTIC_RULES, columns=["semantic_type", "pandas_dtype", "model_dtype", "rule"])) +
             "\n## SQL → pandas\n\n" + _md(pd.DataFrame([{"sql": k, "pandas": v} for k, v in contract.raw["contract"]["sql_to_pandas"].items()])) +
             "\n## Declared source date formats (text cells; trial order)\n\n" +
             _md(pd.DataFrame([{"order": i + 1, "strptime_format": f, "example": pd.Timestamp("2024-02-01").strftime(f), "reads_as": "2024-02-01"}
                               for i, f in enumerate(contract.date_formats)])) +
             "\nReal Excel and Parquet date cells are taken as they are. The audit reports which format read each column "
             "(`datatype_audit.source_date_formats`).\n" +
             "\n## Predictor columns (eFalls baseline and Phase-2 candidates)\n\n" + _md(pred) +
             "\n## eFalls baseline predictors (three types)\n\n" +
             _md(mt[mt["include_in_baseline"]][["canonical_feature", "meuhedet_source_column", "raw_dtype", "canonical_dtype", "model_dtype", "missing_rule", "allowed_values"]]))
    files[OUT / "DATATYPE_CONTRACT.md"] = dt_md
    return files


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    files = build()
    if a.check:
        stale = [p for p, text in files.items() if not p.exists() or p.read_text(encoding="utf-8") != text]
        if stale:
            print("out of date: " + ", ".join(str(p.relative_to(ROOT)) for p in stale), file=sys.stderr)
            return 1
        print("docs/meuhedet tables are current")
        return 0
    for p, text in files.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
