"""Design-time provenance accounting of the Phase 2 inputs (no data): which of the 221 contract columns and 93 engineered features CAN be
SAFE (their source has a documented record date; the extract then decides SAFE / UNSAFE / UNRESOLVED) and which can NEVER be SAFE in this
extract (no record date, first-entry date only, undocumented meaning, unknown timing, forbidden / post-index). Uses only the contract, the
data dictionary and the unchanged D-00 evidence standard. Writes planning/PROVENANCE_ACCOUNTING.md.

    python tools/phase2_design_accounting.py
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

RANK = {"UNSAFE": 4, "UNRESOLVED_OR_UNSAFE": 3, "UNRESOLVED": 2, "CAN_BE_SAFE": 1, "SAFE": 0}
TEXT = {"SAFE": "SAFE by design (static, documented attribute)", "CAN_BE_SAFE": "can be SAFE (dated source; the extract decides)",
        "UNRESOLVED": "never SAFE here: no record date / undocumented meaning / unknown timing",
        "UNRESOLVED_OR_UNSAFE": "never SAFE here: first-entry date only or undocumented record date (UNRESOLVED, or UNSAFE if a date is on/after index)",
        "UNSAFE": "never a predictor: forbidden / post-index / follow-up"}


def main() -> int:
    from falls_ml.d00.dependency import load_d00_config
    from falls_ml.data.meuhedet_wide import load_wide_contract, load_wide_mapping
    from falls_ml.eda.dictionary import load_data_dictionary
    from falls_ml.phase2.config import load_catalogue, load_phase2_config

    cfg = load_phase2_config()
    mapping = load_wide_mapping()
    contract = load_wide_contract(mapping.contract_path)
    dic = load_data_dictionary("configs/meuhedet/wide_v1_data_dictionary.yaml", contract)
    d00 = load_d00_config(cfg["d00_config"], contract=contract, dictionary=dic)
    cat = load_catalogue(cfg["features"], contract, dic, mapping)

    def own(col: str) -> str:
        c, d = contract.get(col), dic.columns[col]
        kind, date = d00.source_evidence[d["source"]], dic.record_date(col)
        if c.role == "FORBIDDEN_LEAKAGE" or c.timing == "post_index" or kind == "POST_INDEX":
            return "UNSAFE"
        if c.timing == "unknown":
            return "UNRESOLVED"
        if kind == "STATIC_ATTRIBUTE":
            return "SAFE" if d["status"] == "DOCUMENTED" else "UNRESOLVED"
        if kind in ("NO_RECORD_DATE", "NOT_A_PREDICTOR_SOURCE") or not date or date not in contract.names:
            return "UNRESOLVED"
        if kind == "SUFFICIENT_ONLY_RECORD_DATE" or dic.columns.get(date, {}).get("status") != "DOCUMENTED":
            return "UNRESOLVED_OR_UNSAFE"
        return "CAN_BE_SAFE"

    def trace(col: str, stack: tuple[str, ...] = ()) -> str:
        s = [own(col)] + [trace(p, (*stack, col)) for p in d00.derived_from.get(col, {}).get("from", []) if p not in stack]
        return max(s, key=lambda x: RANK[x])

    worst = lambda cols: max((trace(c) for c in cols), key=lambda x: RANK[x])  # noqa: E731
    raw = Counter(trace(c.name) for c in contract.columns)
    roles = Counter(c.role for c in contract.columns)
    feats = [(f, worst(f.inputs)) for f in cat.features]
    fcount = Counter(s for _, s in feats)
    base = {m.canonical: worst(m.source_columns) for m in mapping.features if m.include_in_baseline and m.canonical in mapping.feature_sets()["extended"]}
    L = ["# Phase 2 provenance accounting (design time; exact; no data)", "",
         "Generated by `python tools/phase2_design_accounting.py` from the contract, the data dictionary and the unchanged D-00 evidence standard. "
         "It says which inputs CAN be SAFE and which can NEVER be SAFE in this extract. The real SAFE / UNSAFE / UNRESOLVED counts depend on "
         "the record dates of TRAIN + VALIDATION rows and are printed by the preflight (`--preflight`) and written to `COLUMN_FUNNEL.csv`.", "",
         f"## Raw contract columns: {sum(raw.values())}", "", "| Class | Columns |", "|---|---|"]
    L += [f"| {TEXT[k]} | {raw.get(k, 0)} |" for k in RANK if raw.get(k, 0)]
    L += ["", "Contract roles: " + ", ".join(f"{k} {v}" for k, v in sorted(roles.items())), "",
          f"## Engineered candidate features: {len(feats)}", "", "| Class | Features |", "|---|---|"]
    L += [f"| {TEXT[k]} | {fcount.get(k, 0)} |" for k in RANK if fcount.get(k, 0)]
    L += ["", "| Domain | can be SAFE | never SAFE here |", "|---|---|---|"]
    for d in cat.domains:
        fs = [s for f, s in feats if f.domain == d]
        L.append(f"| {d} | {sum(1 for s in fs if s in ('SAFE', 'CAN_BE_SAFE'))} | {sum(1 for s in fs if s not in ('SAFE', 'CAN_BE_SAFE'))} |")
    L += ["", "Never SAFE here (enter only EXPLORATORY_UNRESOLVED_SENSITIVITY): " +
          ", ".join(f.name for f, s in feats if s not in ("SAFE", "CAN_BE_SAFE")), "",
          f"## BASELINE_15 predictors: {len(base)}", "", "| Predictor | Class |", "|---|---|"]
    L += [f"| {k} | {TEXT[v]} |" for k, v in base.items()]
    n_can = sum(1 for v in base.values() if v in ("SAFE", "CAN_BE_SAFE"))
    L += ["", f"SAFE_BASE can therefore hold at most {n_can} predictors; the other {len(base) - n_can} are structurally UNRESOLVED in this extract "
          "and appear only in HISTORICAL_BASELINE_15 and the exploratory sensitivity.", ""]
    out = ROOT / "planning" / "PROVENANCE_ACCOUNTING.md"
    out.write_text("\n".join(L), encoding="utf-8", newline="\n")
    print(f"wrote {out.relative_to(ROOT)}: raw {dict(raw)}, engineered {dict(fcount)}, baseline can-be-SAFE {n_can}/{len(base)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
