"""Windows portability guards. Windows 10/11 x64 (CMD, ANSI code pages such as cp1252/cp1255, 260-character paths) is a supported
runtime, but development and CI run on macOS, so Windows-only failure modes are caught here statically (AST, never regex) or by
simulating the Windows behaviour on the current OS.

Static rules (``src/``, ``tests/``, ``tools/``, ``scripts/handoff/``):
- every text-mode ``open``/``Path.open``/``read_text``/``write_text``/``NamedTemporaryFile``/``TextIOWrapper`` passes ``encoding``
  (the Windows default is the ANSI code page, not UTF-8);
- ``subprocess`` text mode passes ``encoding``; no ``shell=True``, ``os.system``, ``os.popen`` or ``subprocess.getoutput``;
- no Unix-only modules (``fcntl``, ``resource``, ``pwd``, ``grp``, ``termios``, ...) or POSIX-only ``os``/``signal`` calls;
- artifacts written by ``src/`` and generated by ``tools/`` use LF line endings (``newline="\\n"``, ``lineterminator="\\n"``),
  so outputs are byte-identical across operating systems;
- tests that create symlinks handle ``OSError`` or skip on Windows;
- no reserved Windows file names, invalid characters, trailing dots/spaces or case-only collisions in the shipped tree.
"""

from __future__ import annotations

import ast
import hashlib
import io
import json
import os
import re
import shutil
import subprocess
import sys
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
import pytest
import yaml

from tests.helpers.subprocesses import utf8_env

ROOT = Path(__file__).resolve().parents[2]
SCANNED_DIRS = ("src", "tests", "tools", "scripts/handoff")
LF_ARTIFACT_DIRS = ("src", "tools")
SHIPPED_DIRS = ("src", "configs", "docs", "tests", "tools", "scripts", "data")
NOT_SHIPPED_PARTS = {"__pycache__", ".pytest_cache"}
UNIX_ONLY_MODULES = {"fcntl", "resource", "pwd", "grp", "termios", "tty", "pty", "posix", "syslog", "crypt", "curses"}
POSIX_ONLY_ATTRIBUTES = {("os", n) for n in ("fork", "forkpty", "getuid", "geteuid", "getgid", "getegid", "setsid", "killpg", "chown",
                                             "lchown", "mkfifo", "getpgid", "setuid", "setgid", "wait3", "wait4")} | \
                        {("signal", n) for n in ("alarm", "SIGALRM", "SIGHUP", "SIGKILL", "SIGUSR1", "SIGUSR2", "SIGQUIT", "setitimer")}
SHELL_CALLS = {("os", "system"), ("os", "popen"), ("subprocess", "getoutput"), ("subprocess", "getstatusoutput")}
SUBPROCESS_FUNCS = {"run", "Popen", "check_output", "call", "check_call"}
NON_PATH_OPEN_RECEIVERS = {"zipfile", "tarfile", "gzip", "bz2", "lzma", "webbrowser", "os", "Image", "wave", "shelve", "dbm", "codecs"}
MODE_LITERAL = re.compile(r"[rwaxbtU+]{1,4}")
RESERVED_STEMS = {"con", "prn", "aux", "nul", *(f"com{i}" for i in range(1, 10)), *(f"lpt{i}" for i in range(1, 10))}
INVALID_NAME_CHARS = set('<>:"|?*\\')
MAX_SHIPPED_RELATIVE_PATH = 100   # + a ~60-character project folder stays far below MAX_PATH (260)
HEBREW = "\u05de\u05d0\u05d5\u05d7\u05d3\u05ea"


# ============================================================================ AST scanning helpers
@dataclass(frozen=True)
class Site:
    path: str
    line: int
    function: str
    rule: str

    def __str__(self) -> str:
        return f"{self.path}:{self.line} ({self.function}): {self.rule}"


def _python_files(dirs: tuple[str, ...]) -> list[Path]:
    return sorted(p for d in dirs for p in (ROOT / d).rglob("*.py") if "__pycache__" not in p.parts)


def _rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def _has_kw(call: ast.Call, name: str) -> bool:
    return any(k.arg == name for k in call.keywords)


def _kw(call: ast.Call, name: str) -> ast.expr | None:
    return next((k.value for k in call.keywords if k.arg == name), None)


def _literal_str(node: ast.expr | None) -> str | None:
    return node.value if isinstance(node, ast.Constant) and isinstance(node.value, str) else None


def _is_false(node: ast.expr | None) -> bool:
    return isinstance(node, ast.Constant) and node.value in (False, None, 0)


def _dotted(node: ast.expr) -> tuple[str, str] | None:
    """('module', 'attr') for ``module.attr`` expressions."""
    if isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name):
        return node.value.id, node.attr
    return None


class _Visitor(ast.NodeVisitor):
    """Walks one module keeping the enclosing function name and whether we are inside ``try: ... except OSError``."""

    def __init__(self) -> None:
        self.functions: list[ast.FunctionDef | ast.AsyncFunctionDef] = []
        self.oserror_try_depth = 0
        self.calls: list[tuple[ast.Call, str, bool, list[ast.expr]]] = []
        self.imports: list[tuple[int, str, str]] = []
        self.attributes: list[tuple[ast.Attribute, str]] = []

    def _function(self) -> str:
        return self.functions[-1].name if self.functions else "<module>"

    def visit_FunctionDef(self, node: ast.FunctionDef | ast.AsyncFunctionDef) -> None:
        self.functions.append(node)
        self.generic_visit(node)
        self.functions.pop()

    visit_AsyncFunctionDef = visit_FunctionDef

    def visit_Try(self, node: ast.Try) -> None:
        catches = any(h.type is None or any(isinstance(n, ast.Name) and n.id in {"OSError", "Exception", "NotImplementedError"}
                                            for n in ast.walk(h.type)) for h in node.handlers)
        self.oserror_try_depth += catches
        for stmt in node.body:
            self.visit(stmt)
        self.oserror_try_depth -= catches
        for part in (*node.handlers, *node.orelse, *node.finalbody):
            self.visit(part)

    visit_TryStar = visit_Try

    def visit_Call(self, node: ast.Call) -> None:
        decorators = [d for f in self.functions for d in f.decorator_list]
        self.calls.append((node, self._function(), self.oserror_try_depth > 0, decorators))
        self.generic_visit(node)

    def visit_Import(self, node: ast.Import) -> None:
        self.imports += [(node.lineno, alias.name.split(".")[0], self._function()) for alias in node.names]

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        if node.module and node.level == 0:
            self.imports.append((node.lineno, node.module.split(".")[0], self._function()))

    def visit_Attribute(self, node: ast.Attribute) -> None:
        self.attributes.append((node, self._function()))
        self.generic_visit(node)


def _visit(path: Path) -> _Visitor:
    visitor = _Visitor()
    visitor.visit(ast.parse(path.read_bytes(), filename=str(path)))
    return visitor


def _open_mode(call: ast.Call, positional_index: int) -> str | None:
    """Literal mode of an open-like call ('r' when omitted); None when the mode is not a literal."""
    mode = _kw(call, "mode")
    if mode is None and len(call.args) > positional_index:
        mode = call.args[positional_index]
    if mode is None:
        return "r"
    return _literal_str(mode)


def text_io_without_encoding(path: Path) -> list[Site]:
    """Text-mode file and pipe I/O that would use the Windows ANSI code page."""
    rel, sites = _rel(path), []
    for call, function, _, _ in _visit(path).calls:
        func = call.func
        name = func.id if isinstance(func, ast.Name) else func.attr if isinstance(func, ast.Attribute) else None
        dotted = _dotted(func)
        encoded = _has_kw(call, "encoding")
        rule = None
        if name in {"read_text", "write_text"} and isinstance(func, ast.Attribute):
            if not encoded and len(call.args) <= (0 if name == "read_text" else 1):
                rule = f"{name}() without encoding"
        elif name == "open" and (isinstance(func, ast.Name) or dotted == ("io", "open")):
            mode = _open_mode(call, 1)
            if not encoded and len(call.args) <= 3 and (mode is None or "b" not in mode):
                rule = f"open() text mode {mode!r} without encoding"
        elif name == "open" and isinstance(func, ast.Attribute) and (dotted is None or dotted[0] not in NON_PATH_OPEN_RECEIVERS):
            first = _literal_str(call.args[0]) if call.args else None
            if call.args and first is not None and not MODE_LITERAL.fullmatch(first):
                continue  # e.g. ZipFile.open("member"): not a Path.open mode
            mode = _open_mode(call, 0)
            if not encoded and len(call.args) <= 2 and (mode is None or "b" not in mode):
                rule = f"Path.open() text mode {mode!r} without encoding"
        elif dotted == ("os", "fdopen"):
            mode = _open_mode(call, 1)
            if not encoded and (mode is None or "b" not in mode):
                rule = f"os.fdopen() text mode {mode!r} without encoding"
        elif name in {"NamedTemporaryFile", "TemporaryFile", "SpooledTemporaryFile"}:
            mode = _open_mode(call, 1 if name == "SpooledTemporaryFile" else 0)
            if mode == "r":
                mode = "w+b"  # tempfile default
            if not encoded and (mode is None or "b" not in mode):
                rule = f"{name}() text mode {mode!r} without encoding"
        elif name == "TextIOWrapper":
            if not encoded and len(call.args) < 2:
                rule = "TextIOWrapper() without encoding"
        elif name in SUBPROCESS_FUNCS and (dotted is None or dotted[0] == "subprocess"):
            text = [_kw(call, k) for k in ("text", "universal_newlines") if _has_kw(call, k)]
            if any(not _is_false(t) for t in text) and not encoded:
                rule = f"subprocess.{name}() text mode without encoding"
        if rule:
            sites.append(Site(rel, call.lineno, function, rule))
    return sites


def lf_artifact_writes(path: Path) -> list[Site]:
    """Text written by src/ and tools/ must use LF on every OS (Windows text mode and pandas default to CRLF)."""
    rel, sites = _rel(path), []
    for call, function, _, _ in _visit(path).calls:
        func = call.func
        if not isinstance(func, ast.Attribute):
            continue
        if func.attr == "write_text" and not _has_kw(call, "newline"):
            sites.append(Site(rel, call.lineno, function, 'write_text() without newline="\\n"'))
        elif func.attr == "to_csv" and not _has_kw(call, "lineterminator"):
            sites.append(Site(rel, call.lineno, function, 'DataFrame.to_csv() without lineterminator="\\n"'))
        elif func.attr == "open" and _dotted(func) is None:
            mode = _open_mode(call, 0)
            if mode is not None and "b" not in mode and set(mode) & set("wax") and not _has_kw(call, "newline"):
                sites.append(Site(rel, call.lineno, function, f'Path.open({mode!r}) without newline="\\n"'))
    return sites


def shell_and_posix_only(path: Path) -> list[Site]:
    rel, sites, visitor = _rel(path), [], _visit(path)
    for call, function, _, _ in visitor.calls:
        if _has_kw(call, "shell") and not _is_false(_kw(call, "shell")):
            sites.append(Site(rel, call.lineno, function, "shell=True (CMD quoting and injection differ from POSIX shells)"))
        if _dotted(call.func) in SHELL_CALLS:
            sites.append(Site(rel, call.lineno, function, f"{'.'.join(_dotted(call.func))}() runs a shell"))
    sites += [Site(rel, line, function, f"Unix-only module {module!r}") for line, module, function in visitor.imports if module in UNIX_ONLY_MODULES]
    sites += [Site(rel, node.lineno, function, f"POSIX-only {'.'.join(_dotted(node))}") for node, function in visitor.attributes
              if _dotted(node) in POSIX_ONLY_ATTRIBUTES]
    return sites


def unguarded_symlinks(path: Path) -> list[Site]:
    """Symlink creation needs admin rights or Developer Mode on Windows: handle OSError or skip on win32."""
    rel, sites = _rel(path), []
    for call, function, in_oserror_try, decorators in _visit(path).calls:
        func = call.func
        name = func.attr if isinstance(func, ast.Attribute) else func.id if isinstance(func, ast.Name) else None
        if name not in {"symlink_to", "symlink", "hardlink_to", "link"} or (name in {"symlink", "link"} and _dotted(func) != ("os", name)):
            continue
        skips_windows = any("skipif" in ast.unparse(d) and ("win32" in ast.unparse(d) or "os.name" in ast.unparse(d)) for d in decorators)
        if not (in_oserror_try or skips_windows):
            sites.append(Site(rel, call.lineno, function, f"{name}() without OSError handling or a Windows skip"))
    return sites


def _shipped_paths() -> Iterator[Path]:
    yield from (p for p in ROOT.iterdir() if p.is_file() and not p.name.startswith("."))
    for top in SHIPPED_DIRS:
        for p in sorted((ROOT / top).rglob("*")):
            if not NOT_SHIPPED_PARTS & set(p.parts) and not any(part.endswith(".egg-info") for part in p.parts):
                yield p


def windows_name_problems(paths: list[Path]) -> list[str]:
    problems = []
    by_folder: dict[tuple[str, str], list[str]] = {}
    for p in paths:
        rel = p.relative_to(ROOT).as_posix()
        name = p.name
        if name.split(".")[0].rstrip(" ").lower() in RESERVED_STEMS:
            problems.append(f"{rel}: reserved Windows device name")
        if INVALID_NAME_CHARS & set(name) or any(ord(c) < 32 for c in name):
            problems.append(f"{rel}: character not allowed in Windows file names")
        if name.endswith((".", " ")):
            problems.append(f"{rel}: trailing dot or space is dropped by Windows")
        if len(rel) > MAX_SHIPPED_RELATIVE_PATH:
            problems.append(f"{rel}: {len(rel)} characters (limit {MAX_SHIPPED_RELATIVE_PATH}; Windows MAX_PATH is 260 including the folder)")
        by_folder.setdefault((p.parent.relative_to(ROOT).as_posix(), name.lower()), []).append(name)
    problems += [f"{folder}: names differ only in case {sorted(names)}" for (folder, _), names in by_folder.items() if len(names) > 1]
    return problems


# ============================================================================ static tests
@pytest.mark.parametrize("path", _python_files(SCANNED_DIRS), ids=_rel)
def test_text_io_always_passes_an_encoding(path):
    sites = text_io_without_encoding(path)
    assert not sites, "pass encoding=\"utf-8\" (Windows defaults to the ANSI code page):\n" + "\n".join(map(str, sites))


@pytest.mark.parametrize("path", _python_files(LF_ARTIFACT_DIRS), ids=_rel)
def test_written_artifacts_use_lf_line_endings(path):
    sites = lf_artifact_writes(path)
    assert not sites, "artifacts must be byte-identical across operating systems:\n" + "\n".join(map(str, sites))


@pytest.mark.parametrize("path", _python_files(SCANNED_DIRS), ids=_rel)
def test_no_shell_invocations_or_unix_only_apis(path):
    sites = shell_and_posix_only(path)
    assert not sites, "\n".join(map(str, sites))


@pytest.mark.parametrize("path", _python_files(("tests",)), ids=_rel)
def test_symlink_creation_is_guarded_for_windows(path):
    sites = unguarded_symlinks(path)
    assert not sites, "\n".join(map(str, sites))


def test_shipped_tree_has_portable_file_names():
    problems = windows_name_problems(list(_shipped_paths()))
    assert not problems, "\n".join(problems)


def test_scanners_detect_violations(tmp_path, monkeypatch):
    """The scanners must flag the patterns they exist for (a scanner that finds nothing proves nothing)."""
    monkeypatch.setattr(sys.modules[__name__], "ROOT", tmp_path)
    bad = tmp_path / "src" / "bad.py"
    bad.parent.mkdir()
    bad.write_text(
        "import fcntl, os, subprocess, tempfile, io\nfrom pathlib import Path\n"
        "def f(p, zf):\n"
        "    open(p).read(); open(p, 'w'); Path(p).read_text(); Path(p).write_text('x'); Path(p).open('a')\n"
        "    tempfile.NamedTemporaryFile('w'); io.TextIOWrapper(p); os.fdopen(3, 'w')\n"
        "    subprocess.run(['x'], text=True); subprocess.run('x', shell=True); os.system('x'); os.getuid()\n"
        "    p.to_csv('a.csv'); Path(p).symlink_to(p)\n"
        "    open(p, 'rb'); open(p, encoding='utf-8'); Path(p).read_text('utf-8'); zf.open('member.txt'); Path(p).open('rb')\n"
        "    subprocess.run(['x'], text=True, encoding='utf-8'); tempfile.NamedTemporaryFile()\n", encoding="utf-8")
    encoding_rules = [s.rule for s in text_io_without_encoding(bad)]
    assert len(encoding_rules) == 9, encoding_rules
    assert len(lf_artifact_writes(bad)) == 3
    assert sorted(s.rule.split()[0] for s in shell_and_posix_only(bad)) == ["POSIX-only", "Unix-only", "os.system()", "shell=True"]
    assert len(unguarded_symlinks(bad)) == 1
    # join as text: on Windows `path / "a:b.csv"` treats "a:" as a drive and discards the folder
    names = [Path(f"{tmp_path / 'src'}{os.sep}{n}") for n in ("aux.txt", "COM1", "report.", "a:b.csv", "Readme.md", "README.md")]
    problems = windows_name_problems(names)
    assert len(problems) == 5 and any("differ only in case" in p for p in problems)


# ============================================================================ runtime: console streams
def test_cli_console_streams_backslashreplace_on_ansi_code_pages(monkeypatch):
    from falls_ml import cli

    # newline="\n": on Windows a default TextIOWrapper writes "\r\n"; this test is about encoding, not line endings
    cp1252_out, cp1252_err = (io.TextIOWrapper(io.BytesIO(), encoding="cp1252", newline="\n") for _ in range(2))
    utf8 = io.TextIOWrapper(io.BytesIO(), encoding="utf-8", newline="\n")
    monkeypatch.setattr(sys, "stdout", cp1252_out)
    monkeypatch.setattr(sys, "stderr", cp1252_err)
    cli._safe_console_streams()
    print(f"dataset_version meuhedet-{HEBREW}-v1 \u2013 ok")
    sys.stdout.flush()
    assert cp1252_out.buffer.getvalue() == b"dataset_version meuhedet-\\u05de\\u05d0\\u05d5\\u05d7\\u05d3\\u05ea-v1 \x96 ok\n"
    assert cp1252_err.errors == "backslashreplace"
    monkeypatch.setattr(sys, "stdout", utf8)
    cli._safe_console_streams()
    assert utf8.errors == "strict", "UTF-8 streams are left alone"


def test_cli_prints_non_ascii_table_through_a_cp1252_pipe(tmp_path):
    """``python -m falls_ml compare > out.txt`` from plain CMD on a cp1252 system with a Hebrew dataset_version."""
    from tests.helpers.fake_run import make_fake_run

    make_fake_run(tmp_path / "runs", kind="efalls_published_scoring", model="efalls_published", seed=1,
                  dataset_version=f"meuhedet-{HEBREW}-v1", n_test=200)
    env = {k: v for k, v in os.environ.items() if k not in {"PYTHONUTF8", "PYTHONIOENCODING", "PYTHONLEGACYWINDOWSSTDIO"}}
    env.update(PYTHONIOENCODING="cp1252", PYTHONUTF8="0", MPLBACKEND="Agg")
    result = subprocess.run([sys.executable, "-m", "falls_ml", "compare", "--runs-dir", "runs", "--out", "reports", "--n-bootstrap", "5"],
                            cwd=tmp_path, capture_output=True, env=env, timeout=300, check=False)
    stdout, stderr = result.stdout.decode("cp1252"), result.stderr.decode("cp1252")
    assert result.returncode == 0, stderr[-3000:]
    assert "meuhedet-\\u05de\\u05d0\\u05d5\\u05d7\\u05d3\\u05ea-v1" in stdout
    assert "UnicodeEncodeError" not in stderr
    table, markdown = (tmp_path / "reports" / "comparison.csv").read_bytes(), (tmp_path / "reports" / "comparison.md").read_bytes()
    assert f"meuhedet-{HEBREW}-v1".encode("utf-8") in table and b"\r" not in table + markdown, "reports stay UTF-8 with LF"


def test_plots_use_the_headless_agg_backend():
    env = {k: v for k, v in utf8_env().items() if k != "MPLBACKEND"}
    code = "import falls_ml.reporting.plots, matplotlib, sys; print(matplotlib.get_backend()); print('matplotlib.pyplot' in sys.modules)"
    result = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True, encoding="utf-8", errors="replace", env=env,
                            timeout=120, check=False)
    assert result.returncode == 0, result.stderr
    assert result.stdout.lower().split() == ["agg", "false"]


# ============================================================================ runtime: CSV input
@pytest.fixture(scope="module")
def spec():
    from falls_ml.features.spec import load_feature_spec

    return load_feature_spec(ROOT / "configs" / "features" / "efalls_v1.yaml")


def test_read_table_accepts_upper_case_extensions_and_utf8_bom(tmp_path, spec):
    from falls_ml.cli import _check_out_suffix, _read_table

    path = tmp_path / "EXTRACT.CSV"
    path.write_bytes("\ufeffresearch_id,sex\n007,female\n".encode("utf-8"))
    df = _read_table(str(path), spec)
    assert list(df.columns) == ["research_id", "sex"] and df.loc[0, "research_id"] == "007"
    pd.DataFrame({"research_id": ["1"]}).to_parquet(tmp_path / "ROWS.PARQUET")
    assert len(_read_table(str(tmp_path / "ROWS.PARQUET"), spec)) == 1
    for out in ("PREDICTIONS.CSV", "scores.Parquet"):
        _check_out_suffix(out)
    with pytest.raises(SystemExit, match="unsupported input format"):
        _read_table(str(tmp_path / "rows.xlsx"), spec)


@pytest.mark.parametrize("encoding", ["utf-16", "cp1255"])
def test_read_table_rejects_non_utf8_csv_with_guidance(tmp_path, spec, encoding):
    from falls_ml.cli import _read_table

    path = tmp_path / "extract.csv"
    path.write_bytes(f"research_id,notes\n1,{HEBREW}\n".encode(encoding))
    with pytest.raises(SystemExit, match="is not UTF-8 encoded.*CSV UTF-8"):
        _read_table(str(path), spec)


# ============================================================================ runtime: artifacts and provenance
def test_source_tree_hash_is_os_independent(tmp_path):
    from falls_ml.artifacts import source_tree_sha256

    # "B.py" < "a.py" only in case-sensitive order (Windows Path ordering is case-insensitive); "data/..." vs "data.py" checks
    # component-wise order; no case-only collisions (macOS and Windows file systems are case-insensitive)
    files = {"a.py": b"x = 1\n", "B.py": b"y = 2\n", "data/synthetic.py": b"import os\n", "data.py": b"z = 3\n", "a-b.py": b"\n"}
    for rel, data in files.items():
        (tmp_path / "lf" / rel).parent.mkdir(parents=True, exist_ok=True)
        (tmp_path / "lf" / rel).write_bytes(data)
        (tmp_path / "crlf" / rel).parent.mkdir(parents=True, exist_ok=True)
        (tmp_path / "crlf" / rel).write_bytes(data.replace(b"\n", b"\r\n"))
    (tmp_path / "lf" / "__pycache__").mkdir()
    (tmp_path / "lf" / "__pycache__" / "a.py").write_bytes(b"ignored")
    expected = hashlib.sha256()
    for rel in sorted(files, key=lambda r: tuple(r.split("/"))):   # case-sensitive component order, "/" separators
        expected.update(rel.encode("utf-8") + files[rel])
    assert source_tree_sha256(tmp_path / "lf") == source_tree_sha256(tmp_path / "crlf") == expected.hexdigest()


def test_definition_file_hash_ignores_crlf_only(tmp_path):
    from falls_ml.artifacts import definition_file_sha256

    lf, crlf, changed = tmp_path / "lf.yaml", tmp_path / "crlf.yaml", tmp_path / "changed.yaml"
    lf.write_bytes(b"a: 1\nb: 2\n")
    crlf.write_bytes(b"a: 1\r\nb: 2\r\n")
    changed.write_bytes(b"a: 1\nb: 3\n")
    assert definition_file_sha256(lf) == definition_file_sha256(crlf) == hashlib.sha256(lf.read_bytes()).hexdigest()
    assert definition_file_sha256(changed) != definition_file_sha256(lf)


def test_csv_json_yaml_artifacts_use_lf_even_with_windows_linesep(tmp_path, monkeypatch):
    from falls_ml.artifacts import write_csv, write_json, write_yaml

    monkeypatch.setattr(os, "linesep", "\r\n")   # pandas uses os.linesep for to_csv when no lineterminator is given
    csv = write_csv(tmp_path / "t.csv", pd.DataFrame({"name": [HEBREW, "b"], "v": [1, 2]}))
    assert csv.read_bytes() == f"name,v\n{HEBREW},1\nb,2\n".encode("utf-8")
    assert b"\r" not in write_json(tmp_path / "t.json", {"a": [1, 2], "h": HEBREW}).read_bytes()
    assert b"\r" not in write_yaml(tmp_path / "t.yaml", {"a": [1, 2], "h": HEBREW}).read_bytes()
    assert not list(tmp_path.glob(".*.tmp"))


def test_replace_file_retries_windows_sharing_violations(tmp_path, monkeypatch):
    from falls_ml import artifacts

    src, dst = tmp_path / "src.json", tmp_path / "dst.json"
    src.write_text("{}", encoding="utf-8")
    real_replace, attempts, sleeps = os.replace, [], []

    def flaky(a, b):
        attempts.append(1)
        if len(attempts) < 3:
            raise PermissionError(13, "The process cannot access the file because it is being used by another process")
        real_replace(a, b)

    monkeypatch.setattr(artifacts.os, "replace", flaky)
    artifacts.replace_file(src, dst, windows=True, sleep=sleeps.append)
    assert dst.read_text(encoding="utf-8") == "{}" and len(attempts) == 3 and sleeps == [0.05, 0.1]

    def locked(a, b):
        raise PermissionError(13, "in use")

    monkeypatch.setattr(artifacts.os, "replace", locked)
    src.write_text("{}", encoding="utf-8")
    with pytest.raises(PermissionError, match="after 10 attempts.*in use by another process") as excinfo:
        artifacts.replace_file(src, dst, windows=True, sleep=sleeps.append)
    assert str(dst) in str(excinfo.value) and max(sleeps) == 0.5
    with pytest.raises(PermissionError, match="^\\[Errno 13\\] in use$"):
        artifacts.replace_file(src, dst, windows=False, sleep=sleeps.append)
    with pytest.raises(PermissionError):
        artifacts.write_json(tmp_path / "out.json", {"a": 1})
    assert not list(tmp_path.glob(".out.json.tmp")), "the temp file is removed when the replace fails"


def test_git_commit_survives_undecodable_output_and_foreign_repositories(tmp_path, monkeypatch):
    from falls_ml import artifacts

    def undecodable(*args, **kwargs):
        raise UnicodeDecodeError("charmap", b"\x9d", 0, 1, "character maps to <undefined>")

    monkeypatch.setattr(artifacts.subprocess, "run", undecodable)
    assert artifacts.git_commit(tmp_path) is None
    monkeypatch.undo()
    git = shutil.which("git")
    if git is None or subprocess.run([git, "--version"], capture_output=True, check=False).returncode != 0:
        pytest.skip("git not available")
    repo = tmp_path / "repo"
    (repo / "handoff").mkdir(parents=True)
    ident = ["-c", "user.name=test", "-c", "user.email=test@example.org", "-c", "core.quotepath=false", "-c", "commit.gpgsign=false"]
    for args in (["init", "-q"], ["add", "-A"], ["commit", "-q", "--allow-empty", "-m", "init"]):
        subprocess.run([git, *ident, *args], cwd=repo, capture_output=True, check=True, env=utf8_env(GIT_CONFIG_NOSYSTEM="1"))
    (repo / f"d{HEBREW}.csv").write_bytes(b"x")
    subprocess.run([git, "config", "core.quotepath", "false"], cwd=repo, capture_output=True, check=True)
    commit = artifacts.git_commit(repo)
    assert commit is not None and re.fullmatch(r"[0-9a-f]{40}-dirty", commit)
    assert artifacts.git_commit(repo / "handoff") is None, "a folder inside an unrelated repository records no commit"


def test_run_ids_stay_short_for_windows_paths(tmp_path):
    from falls_ml.artifacts import RUN_LABEL_MAX_CHARS, create_run_directory, run_label

    assert run_label("efalls_retrained_lasso", "lasso_logistic_cv") == "efalls_retrained_lasso_lasso_logistic_cv"
    assert run_label("logistic_unpenalized__nurse_assessments", "logistic_unpenalized") == "logistic_unpenalized__nurse_assessments"
    assert run_label("efalls_retrained_lasso__random_forest", "random_forest") == "efalls_retrained_lasso__random_forest"
    long_label = run_label("x" * 59 + "_" + "y" * 100, "random_forest")
    assert len(long_label) <= RUN_LABEL_MAX_CHARS and not long_label.endswith("_")
    run = create_run_directory(tmp_path, "a" * 150, "hist_gradient_boosting", config_sha256="c", dataset_sha256="d",
                               created_utc="2026-09-15T00:00:00+00:00")
    assert len(run.run_id) <= 10 + 1 + RUN_LABEL_MAX_CHARS + 1 + 8 and re.fullmatch(r"2026-09-15_a+_[0-9a-f]{8}", run.run_id)
    other = create_run_directory(tmp_path, "a" * 151, "hist_gradient_boosting", config_sha256="c2", dataset_sha256="d",
                                 created_utc="2026-09-15T00:00:00+00:00")
    assert other.run_id != run.run_id, "the hash token keeps truncated ids unique"


@pytest.mark.parametrize("name", ["lasso:v2", "what?", "a b", "trailing.", "-leading", "back\\slash", "for/ward", "x" * 201, ""])
def test_experiment_names_must_be_portable_directory_names(name):
    from falls_ml.config import experiment_config_from_dict
    from falls_ml.errors import ConfigError

    raw = yaml.safe_load((ROOT / "configs" / "experiments" / "fixture" / "efalls_retrained_lasso.yaml").read_text(encoding="utf-8"))
    raw["experiment"]["name"] = name
    with pytest.raises(ConfigError, match="portable directory-name part"):
        experiment_config_from_dict(raw)
    raw["experiment"]["name"] = "efalls_retrained_lasso-v2.1"
    assert experiment_config_from_dict(raw).experiment.name == "efalls_retrained_lasso-v2.1"


def test_recorded_relative_paths_use_forward_slashes(tmp_path):
    from falls_ml.experiment import _ablation_extension_path
    from falls_ml.features.spec import load_feature_spec
    from falls_ml.paths import portable_path, project_relative_posix

    assert portable_path(Path("configs") / "features" / "efalls_v1.yaml") == "configs/features/efalls_v1.yaml"
    assert portable_path(ROOT / "configs") == str(ROOT / "configs")
    spec = load_feature_spec(Path("configs") / "features" / "efalls_v1.yaml", [Path("configs") / "features" / "meuhedet_enhanced_example.yaml"],
                             anchor=ROOT / "configs")
    assert spec.source_paths == ("configs/features/efalls_v1.yaml", "configs/features/meuhedet_enhanced_example.yaml")
    project = tmp_path / "Falls Research" / "falls_ml_handoff"
    (project / "configs").mkdir(parents=True)
    (project / "data" / "fixtures" / "synthetic_v1").mkdir(parents=True)
    run_dir = project / "demo_outputs" / "full" / "runs" / "run1"
    run_dir.mkdir(parents=True)
    assert project_relative_posix(project / "data" / "fixtures" / "synthetic_v1", run_dir) == "data/fixtures/synthetic_v1"
    # a folder outside any project records no relative path; pytest's basetemp may itself live inside a project
    # (the installer runs the suite with --basetemp <project>/demo_outputs/pt), so derive the expectation
    from falls_ml.paths import project_root
    outer = project_root(tmp_path)
    expected = None if outer is None else tmp_path.resolve().relative_to(outer).as_posix()
    assert project_relative_posix(tmp_path, tmp_path) == expected
    assert project_relative_posix(tmp_path, run_dir) is None  # outside the fake project
    base = ROOT / "configs" / "experiments" / "fixture" / "elastic_net_logistic.yaml"
    declared = "configs/features/meuhedet_enhanced_example.yaml"
    assert _ablation_extension_path(declared, tmp_path / "ablation.yaml", base) == declared, "machine-independent step config hash"
    absolute = str(ROOT / declared)
    assert _ablation_extension_path(absolute, tmp_path / "ablation.yaml", base) == absolute
    foreign = project / "configs" / "features"
    foreign.mkdir()
    (foreign / "local_only.yaml").write_text("feature_set: {}\n", encoding="utf-8")
    kept = _ablation_extension_path("configs/features/local_only.yaml", project / "configs" / "ablation.yaml", base)
    assert Path(kept).is_absolute() and Path(kept) == (foreign / "local_only.yaml").resolve(), "ambiguous relative paths are pinned"


def test_json_artifacts_record_no_backslash_relative_paths(tmp_path):
    """Bundle and dataset manifests written here must only contain '/' separators in relative paths."""
    from falls_ml.data.synthetic import generate_synthetic_modeling_dataset

    manifest = generate_synthetic_modeling_dataset(tmp_path / "ds", n_patients=60, seed=3,
                                                   feature_spec_path="configs/features/efalls_v1.yaml")
    text = json.dumps(manifest.to_dict())
    assert "\\\\" not in text.replace(json.dumps(str(tmp_path))[1:-1], "")
    assert b"\r" not in (tmp_path / "ds" / "manifest.json").read_bytes()
