"""Unit tests for the hash-pinned dependency locks, scripts/handoff/lockfile.py and scripts/handoff/prepare_offline.py (no network)."""

from __future__ import annotations

import ast
import hashlib
import importlib.metadata as md
import json
import re
import sys
import tomllib
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
HANDOFF = ROOT / "scripts" / "handoff"
if str(HANDOFF) not in sys.path:
    sys.path.insert(0, str(HANDOFF))

import lockfile  # noqa: E402
import prepare_offline  # noqa: E402

RUNTIME_LOCK = ROOT / "requirements.lock"
BUILD_LOCK = ROOT / "requirements-build.lock"
HASH_A, HASH_B, HASH_C = "a" * 64, "b" * 64, "c" * 64


def _logical(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8").replace("\\\n", " ")
    return [ln.strip() for ln in text.splitlines() if ln.strip() and not ln.strip().startswith("#")]


def _release(version: str) -> tuple[int, ...]:
    return tuple(int(p) for p in re.match(r"^(\d+(?:\.\d+)*)", version).group(1).split("."))


# ----------------------------------------------------------------------------------------------------------- real locks

def test_lock_files_present_and_legacy_lock_removed():
    assert RUNTIME_LOCK.is_file() and BUILD_LOCK.is_file()
    assert not (ROOT / "requirements-lock.txt").exists()


@pytest.mark.parametrize("path", [RUNTIME_LOCK, BUILD_LOCK], ids=lambda p: p.name)
def test_every_logical_line_is_pinned_with_hashes_and_allowed_marker(path):
    strict = re.compile(r'^[a-z0-9][a-z0-9-]*==[0-9][0-9A-Za-z.+!]*( ; sys_platform (==|!=) "win32")?( --hash=sha256:[0-9a-f]{64})+$')
    lines = _logical(path)
    assert lines
    for line in lines:
        assert strict.match(re.sub(r"\s+", " ", line)), line
    reqs = lockfile.parse_lock(path)
    assert len(reqs) == len(lines)
    assert [r.name for r in reqs] == sorted(r.name for r in reqs)
    for req in reqs:
        assert req.hashes and all(re.fullmatch(r"[0-9a-f]{64}", h) for h in req.hashes)
        assert req.marker in (None, *lockfile.ALLOWED_MARKERS)
        assert req.name == lockfile.canonical_name(req.name)


@pytest.mark.parametrize("path", [RUNTIME_LOCK, BUILD_LOCK], ids=lambda p: p.name)
def test_header_states_python_targets_date_and_generator_without_absolute_paths(path):
    text = path.read_text(encoding="utf-8")
    header = "\n".join(ln for ln in text.splitlines() if ln.startswith("#"))
    for needle in ("Python: CPython 3.11 or 3.13", "windows-amd64-cp313", "windows-amd64-cp311", "macos-arm64-cp313",
                   "Generated by: python tools/lock/generate_lock.py"):
        assert needle in header
    assert re.search(r"^# Generated: \d{4}-\d{2}-\d{2}$", header, re.M)
    assert not re.search(r"(/Users/|/home/|/private/|/tmp/|[A-Za-z]:\\)", text)
    assert text.isascii()


def test_pyproject_direct_dependencies_are_locked_and_satisfy_minimums():
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    locked = {r.name: r for r in lockfile.parse_lock(RUNTIME_LOCK)}
    direct = list(project["dependencies"]) + list(project["optional-dependencies"]["test"])
    assert len(direct) == 13  # 9 + openpyxl (Excel wide-table extracts) + Phase 2: xgboost-cpu (Windows) / xgboost (elsewhere), optuna
    markers = {"sys_platform == 'win32'": lockfile.MARKER_WIN32, "sys_platform != 'win32'": lockfile.MARKER_NOT_WIN32}
    for spec in direct:
        m = re.fullmatch(r"([A-Za-z0-9._-]+)\s*>=\s*([0-9.]+)", spec)
        pinned = re.fullmatch(r"([A-Za-z0-9._-]+)==([0-9.]+);\s*(.+)", spec)
        assert m or pinned, f"unexpected dependency spec form {spec!r}; extend this test"
        req = locked.get(lockfile.canonical_name((m or pinned).group(1)))
        assert req is not None, f"{spec} missing from requirements.lock"
        if m:
            assert req.marker is None
            assert _release(req.version) >= _release(m.group(2)), (spec, req.version)
        else:   # a platform-specific exact pin (the same XGBoost version under two distribution names)
            assert req.version == pinned.group(2) and req.marker == markers[pinned.group(3).strip()], (spec, req.version, req.marker)


def test_runtime_pins_equal_versions_installed_in_running_environment():
    for req in lockfile.parse_lock(RUNTIME_LOCK):
        if lockfile.applies(req, sys.platform):
            assert md.version(req.name) == req.version, f"{req.name}: installed {md.version(req.name)} != lock {req.version}"


def test_build_lock_contains_build_tools_consistent_with_runtime_lock():
    build = {r.name: r for r in lockfile.parse_lock(BUILD_LOCK)}
    runtime = {r.name: r for r in lockfile.parse_lock(RUNTIME_LOCK)}
    assert {"pip", "setuptools", "wheel"} <= set(build)
    assert _release(build["setuptools"].version) >= (69,)
    for name, req in build.items():
        if name in runtime:
            assert runtime[name] == req, f"{name} differs between the two locks"
        try:
            installed = md.version(name)
        except md.PackageNotFoundError:  # setuptools/wheel are absent from a development venv created without them
            continue
        assert installed == req.version, f"{name}: installed {installed} != build lock {req.version}"


def test_platform_specific_dependencies_and_binary_wheels_for_both_targets():
    reqs = {r.name: r for r in lockfile.parse_lock(RUNTIME_LOCK)}
    assert reqs["colorama"].marker == lockfile.MARKER_WIN32  # pytest on Windows
    assert reqs["tzdata"].marker == lockfile.MARKER_WIN32  # pandas on Windows
    for name in ("numpy", "pandas", "scipy", "scikit-learn", "statsmodels", "matplotlib", "pyarrow", "pyyaml"):
        assert len(reqs[name].hashes) >= 2, f"{name} needs win_amd64 and macOS arm64 wheel hashes"
    win = {r.name for r in reqs.values() if lockfile.applies(r, "win32")}
    mac = {r.name for r in reqs.values() if lockfile.applies(r, "darwin")}
    assert win - mac == {r.name for r in reqs.values() if r.marker == lockfile.MARKER_WIN32}
    assert mac - win == {r.name for r in reqs.values() if r.marker == lockfile.MARKER_NOT_WIN32}


@pytest.mark.parametrize("platform", ["win32", "darwin"])
def test_write_evaluated_requirements_for_real_lock(tmp_path, platform):
    dest = tmp_path / "sub" / f"req-{platform}.txt"
    written = lockfile.write_evaluated_requirements(RUNTIME_LOCK, dest, platform)
    body = [ln for ln in dest.read_text(encoding="utf-8").splitlines() if not ln.startswith("#")]
    assert body and not any("sys_platform" in ln or ";" in ln or "\\" in ln for ln in body)
    assert written == [r for r in lockfile.parse_lock(RUNTIME_LOCK) if lockfile.applies(r, platform)]
    reparsed = lockfile.parse_lock(dest)
    assert [(r.name, r.version, r.hashes, r.marker) for r in reparsed] == [(r.name, r.version, r.hashes, None) for r in written]
    assert ("colorama" in {r.name for r in reparsed}) is (platform == "win32")


def test_handoff_modules_import_only_the_standard_library():
    local = {p.stem for p in HANDOFF.glob("*.py")}
    for name in ("lockfile.py", "prepare_offline.py"):
        tree = ast.parse((HANDOFF / name).read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            mods = [a.name for a in node.names] if isinstance(node, ast.Import) else [node.module or ""] if isinstance(node, ast.ImportFrom) else []
            for mod in mods:
                top = mod.split(".")[0]
                assert top in sys.stdlib_module_names or top in local or top == "__future__", f"{name} imports {mod}"


# ------------------------------------------------------------------------------------------------------------- parser

SAMPLE = (
    "# header\n\n"
    "Alpha_Pkg==1.0 \\\n    --hash=sha256:" + HASH_A + " \\\n    --hash=sha256:" + HASH_B + "\n    # via something\n"
    'winonly==2.0.post1 ; sys_platform == "win32" \\\n    --hash=sha256:' + HASH_C + "\n"
    'posixonly==3.0 ; sys_platform != "win32" --hash=sha256:' + HASH_A + "\n"
)


def test_parse_sample_with_continuations_markers_and_crlf(tmp_path):
    for newline in ("\n", "\r\n"):
        path = tmp_path / "x.lock"
        path.write_bytes(SAMPLE.replace("\n", newline).encode("utf-8"))
        reqs = lockfile.parse_lock(path)
        assert reqs == [lockfile.Requirement("alpha-pkg", "1.0", (HASH_A, HASH_B), None),
                        lockfile.Requirement("winonly", "2.0.post1", (HASH_C,), lockfile.MARKER_WIN32),
                        lockfile.Requirement("posixonly", "3.0", (HASH_A,), lockfile.MARKER_NOT_WIN32)]


def test_marker_evaluation_for_win32_darwin_and_linux():
    reqs = {r.name: r for r in lockfile.parse_lock_text(SAMPLE)}
    assert [lockfile.applies(reqs["winonly"], p) for p in ("win32", "darwin", "linux")] == [True, False, False]
    assert [lockfile.applies(reqs["posixonly"], p) for p in ("win32", "darwin", "linux")] == [False, True, True]
    assert all(lockfile.applies(reqs["alpha-pkg"], p) for p in ("win32", "darwin"))
    assert lockfile.applies(reqs["alpha-pkg"])
    with pytest.raises(lockfile.LockFileError):
        lockfile.applies(lockfile.Requirement("x", "1", (HASH_A,), 'python_version < "3.14"'), "win32")


def test_write_evaluated_requirements_sample(tmp_path):
    src = tmp_path / "s.lock"
    src.write_text(SAMPLE, encoding="utf-8")
    win = lockfile.write_evaluated_requirements(src, tmp_path / "win.txt", "win32")
    mac = lockfile.write_evaluated_requirements(src, tmp_path / "mac.txt", "darwin")
    assert [r.name for r in win] == ["alpha-pkg", "winonly"] and [r.name for r in mac] == ["alpha-pkg", "posixonly"]
    lines = [ln for ln in (tmp_path / "win.txt").read_text(encoding="utf-8").splitlines() if not ln.startswith("#")]
    assert lines == [f"alpha-pkg==1.0 --hash=sha256:{HASH_A} --hash=sha256:{HASH_B}", f"winonly==2.0.post1 --hash=sha256:{HASH_C}"]


@pytest.mark.parametrize("text, message", [
    ("numpy>=1.0 --hash=sha256:" + HASH_A, "not a hash-pinned"),
    ("numpy==1.0", "not a hash-pinned"),
    ("numpy==1.0 --hash=md5:" + "a" * 32, "not a hash-pinned"),
    ("numpy==1.0 --hash=sha256:" + "A" * 64, "not a hash-pinned"),
    ('numpy==1.0 ; python_version < "3.14" --hash=sha256:' + HASH_A, "not a hash-pinned"),
    ("numpy==1.0 ; sys_platform == 'win32' --hash=sha256:" + HASH_A, "not a hash-pinned"),
    ("numpy[extra]==1.0 --hash=sha256:" + HASH_A, "not a hash-pinned"),
    ("--index-url https://example.invalid/simple", "not a hash-pinned"),
    ("-r other.txt", "not a hash-pinned"),
    ("numpy==1.0 --hash=sha256:" + HASH_A + " # inline comment", "not a hash-pinned"),
    ("PyYAML==6.0 --hash=sha256:" + HASH_A + "\npyyaml==6.0 --hash=sha256:" + HASH_B, "duplicate requirement"),
    ("numpy==1.0 --hash=sha256:" + HASH_A + " --hash=sha256:" + HASH_A, "duplicate hash"),
    ("numpy==1.0 \\\n", "end of file"),
    ("numpy==1.0 \\\n# comment\n    --hash=sha256:" + HASH_A, "runs into a blank or comment"),
    ("# only comments\n\n", "no requirements"),
    ("﻿numpy==1.0 --hash=sha256:" + HASH_A, "byte-order mark"),
])
def test_parser_rejects_malformed_locks(text, message):
    with pytest.raises(lockfile.LockFileError, match=re.escape(message)):
        lockfile.parse_lock_text(text, source="bad.lock")


def test_parse_lock_reports_invalid_utf8(tmp_path):
    path = tmp_path / "bad.lock"
    path.write_bytes(b"numpy==1.0 --hash=sha256:" + HASH_A.encode() + b"\xff\n")
    with pytest.raises(lockfile.LockFileError, match="UTF-8"):
        lockfile.parse_lock(path)


def test_sha256_file_and_wheel_filename(tmp_path):
    path = tmp_path / "blob.bin"
    path.write_bytes(b"falls_ml" * 100000)
    assert lockfile.sha256_file(path) == hashlib.sha256(b"falls_ml" * 100000).hexdigest()
    w = lockfile.parse_wheel_filename("scikit_learn-1.9.1-cp313-cp313-win_amd64.whl")
    assert (w.name, w.version, w.build, w.python_tags, w.abi_tags, w.platform_tags) == ("scikit-learn", "1.9.1", None, ("cp313",), ("cp313",), ("win_amd64",))
    w = lockfile.parse_wheel_filename("six-1.17.0-1-py2.py3-none-any.whl")
    assert (w.name, w.build, w.python_tags) == ("six", "1", ("py2", "py3"))
    for bad in ("numpy-2.5.3.tar.gz", "numpy-2.5.3-cp313-win_amd64.whl"):
        with pytest.raises(ValueError):
            lockfile.parse_wheel_filename(bad)


# ----------------------------------------------------------------------------------------------- prepare_offline (no network)

def _fake_bundle(tmp_path: Path) -> tuple[Path, Path, Path, dict]:
    """Two fake wheels + matching locks + manifest for the Windows target."""
    dest = tmp_path / "offline packages"
    dest.mkdir()
    blobs = {"demo_lib-1.0-cp313-cp313-win_amd64.whl": b"demo-win", "colorama-0.4.6-py2.py3-none-any.whl": b"colorama",
             "pip-26.2.1-py3-none-any.whl": b"pip"}
    digests = {name: hashlib.sha256(data).hexdigest() for name, data in blobs.items()}
    for name, data in blobs.items():
        (dest / name).write_bytes(data)
    runtime = tmp_path / "requirements.lock"
    runtime.write_text(
        "# test\n"
        f"demo-lib==1.0 --hash=sha256:{digests['demo_lib-1.0-cp313-cp313-win_amd64.whl']} --hash=sha256:{HASH_A}\n"
        f'colorama==0.4.6 ; sys_platform == "win32" --hash=sha256:{digests["colorama-0.4.6-py2.py3-none-any.whl"]}\n'
        f'posixonly==1.0 ; sys_platform != "win32" --hash=sha256:{HASH_B}\n', encoding="utf-8")
    build = tmp_path / "requirements-build.lock"
    build.write_text(f"pip==26.2.1 --hash=sha256:{digests['pip-26.2.1-py3-none-any.whl']}\n", encoding="utf-8")
    manifest = {"format": 1, "created_utc": "2026-01-01T00:00:00Z", "target": prepare_offline.target_spec("windows-amd64-cp313")["manifest"],
                "requirements_lock_sha256": lockfile.sha256_file(runtime), "build_lock_sha256": lockfile.sha256_file(build),
                "files": dict(sorted(digests.items()))}
    (dest / prepare_offline.MANIFEST_NAME).write_text(json.dumps(manifest), encoding="utf-8")
    return dest, runtime, build, manifest


def test_windows_target_uses_contract_pip_flags():
    spec = prepare_offline.target_spec("windows-amd64-cp313")
    assert spec["pip_args"] == ["--platform", "win_amd64", "--python-version", "3.13", "--implementation", "cp", "--abi", "cp313"]
    assert spec["manifest"] == {"name": "windows-amd64-cp313", "platform_tags": ["win_amd64"], "python_version": "3.13", "implementation": "cp", "abi": "cp313"}
    assert spec["sys_platform"] == "win32"
    with pytest.raises(prepare_offline.OfflineError):
        prepare_offline.target_spec("linux")


def test_verify_bundle_accepts_matching_bundle_and_reports_problems(tmp_path):
    dest, runtime, build, manifest = _fake_bundle(tmp_path)
    assert prepare_offline.verify_bundle(dest, runtime, build, sys_platform="win32") == []
    assert any("this computer is darwin" in p for p in prepare_offline.verify_bundle(dest, runtime, build, sys_platform="darwin"))
    (dest / "colorama-0.4.6-py2.py3-none-any.whl").write_bytes(b"tampered")
    assert any("not listed in the lock" in p for p in prepare_offline.verify_bundle(dest, runtime, build, sys_platform="win32"))
    (dest / "colorama-0.4.6-py2.py3-none-any.whl").write_bytes(b"colorama")
    runtime.write_text(runtime.read_text(encoding="utf-8") + "# edited\n", encoding="utf-8")
    assert any("different requirements.lock" in p for p in prepare_offline.verify_bundle(dest, runtime, build, sys_platform="win32"))
    assert prepare_offline.verify_bundle(tmp_path / "missing", runtime, build, sys_platform="win32")[0].endswith("not found")


def test_check_wheels_detects_missing_extra_and_incompatible_wheels(tmp_path):
    dest, runtime, build, _ = _fake_bundle(tmp_path)
    reqs = prepare_offline.applicable_requirements(runtime, build, "win32")
    assert set(reqs) == {"demo-lib", "colorama", "pip"}
    (dest / "pip-26.2.1-py3-none-any.whl").unlink()
    (dest / "stray.txt").write_text("x", encoding="utf-8")
    with pytest.raises(prepare_offline.OfflineError) as err:
        prepare_offline.check_wheels(dest, reqs, "windows-amd64-cp313")
    assert "missing wheel for pip==26.2.1" in str(err.value) and "unexpected entry stray.txt" in str(err.value)
    mac_dir = tmp_path / "mac"
    mac_dir.mkdir()
    (mac_dir / "demo_lib-1.0-cp313-cp313-macosx_11_0_arm64.whl").write_bytes(b"a")
    fake = {"demo-lib": [lockfile.Requirement("demo-lib", "1.0", (hashlib.sha256(b"a").hexdigest(),))]}
    with pytest.raises(prepare_offline.OfflineError, match="not compatible with windows-amd64-cp313"):
        prepare_offline.check_wheels(mac_dir, fake, "windows-amd64-cp313")
    assert prepare_offline.check_wheels(mac_dir, fake, "current") == {"demo_lib-1.0-cp313-cp313-macosx_11_0_arm64.whl": hashlib.sha256(b"a").hexdigest()}


def test_planned_removals_only_touches_manifest_listed_files(tmp_path):
    empty = tmp_path / "empty"
    empty.mkdir()
    assert prepare_offline.planned_removals(empty, force=False) == []
    assert prepare_offline.planned_removals(tmp_path / "does-not-exist", force=False) == []
    dest, _, _, manifest = _fake_bundle(tmp_path)
    with pytest.raises(prepare_offline.OfflineError, match="not empty"):
        prepare_offline.planned_removals(dest, force=False)
    planned = prepare_offline.planned_removals(dest, force=True)
    assert sorted(p.name for p in planned) == sorted([*manifest["files"], prepare_offline.MANIFEST_NAME])
    (dest / "notes.txt").write_text("user file", encoding="utf-8")
    with pytest.raises(prepare_offline.OfflineError, match="notes.txt"):
        prepare_offline.planned_removals(dest, force=True)
    (dest / "notes.txt").unlink()
    manifest["files"]["../outside.whl"] = HASH_A
    (dest / prepare_offline.MANIFEST_NAME).write_text(json.dumps(manifest), encoding="utf-8")
    with pytest.raises(prepare_offline.OfflineError, match="invalid file names"):
        prepare_offline.planned_removals(dest, force=True)
    (dest / prepare_offline.MANIFEST_NAME).unlink()
    with pytest.raises(prepare_offline.OfflineError, match="no OFFLINE_MANIFEST.json"):
        prepare_offline.planned_removals(dest, force=True)
    assert len(list(dest.iterdir())) == 3  # nothing was deleted by any check


def test_verify_only_cli_exit_codes(tmp_path, capsys):
    dest, runtime, build, _ = _fake_bundle(tmp_path)
    args = ["--verify-only", "--dest", str(dest), "--lock", str(runtime), "--build-lock", str(build)]
    expected = 0 if sys.platform == "win32" else 1
    assert prepare_offline.main(args) == expected
    assert prepare_offline.main(["--verify-only", "--dest", str(tmp_path / "nothing"), "--lock", str(runtime), "--build-lock", str(build)]) == 1
    assert "not usable" in capsys.readouterr().err


def test_child_pip_environment_is_utf8_without_install_target_overrides(monkeypatch):
    for name, value in (("PIP_USER", "1"), ("PIP_TARGET", "/elsewhere"), ("PIP_PREFIX", "/prefix"), ("PYTHONPATH", "/leak"),
                        ("PIP_INDEX_URL", "https://mirror.example/simple"), ("PIP_EXTRA_INDEX_URL", "https://extra.example/simple"),
                        ("HTTPS_PROXY", "http://proxy.example:8080")):
        monkeypatch.setenv(name, value)
    env = prepare_offline.child_env()
    assert not {"PIP_USER", "PIP_TARGET", "PIP_PREFIX", "PYTHONPATH"} & set(env)
    assert env["PYTHONUTF8"] == "1" and env["PYTHONIOENCODING"] == "utf-8"
    assert (env["PIP_INDEX_URL"], env["PIP_EXTRA_INDEX_URL"], env["HTTPS_PROXY"]) == (
        "https://mirror.example/simple", "https://extra.example/simple", "http://proxy.example:8080"), "index and proxy settings reach pip"


@pytest.mark.parametrize("target", ["windows-amd64-cp313", "current"])
def test_next_steps_name_the_setup_commands_and_force(tmp_path, monkeypatch, capsys, target):
    manifest = {"files": {}, "target": {"name": target}}
    monkeypatch.setattr(prepare_offline, "prepare", lambda *args, **kwargs: manifest)
    assert prepare_offline.main(["--target", target, "--dest", str(tmp_path / "offline_packages")]) == 0
    out = capsys.readouterr().out
    assert "setup_windows.cmd --offline" in out and "--force" in out and "--target windows-amd64-cp313 --force" in out
    assert ("bash scripts/posix/setup.sh --offline" in out) is (target == "current")
    assert "scripts/posix/setup.sh --offline (macOS)" not in out.replace("bash scripts/posix/setup.sh", "")
